### ISSUE TITLE
Dynamically set contract gas defaults based on client block limit

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#1213]
Ganache has a default gas limit of ~6700000 and Truffle hard-codes that as the default in `truffle-config` unless it's over ridden by a preference defined in the network config. This leads to a lot of confusion:
+ `Exceeds block gas limit` when transitioning from ganache-cli to Ropsten (where limit is low)
+ Running ganache-cli at the command line with a higher gas limit and *still* running out of gas (@shkfnly raised this in slack yesterday)

For V5 we've implemented gas estimation at truffle-contract but it's disabled in the truffle context because the client estimates are sometimes wildly off. 

Ideally we should ask the client what its limit is and use that. But this is a little complicated...needs investigation.

**Comment by gnidan** [comment]
Closing this as won't-fix, since it's likely not safe to use the block limit anymore. Instead, we're moving forward with using the estimated gas value (with a buffer).

See #3992 for the main issue, or PR #4296, where the work is happening to implement this behavior.

(🤞 that this estimation strategy won't be too wildly inaccurate and we won't have to reconsider this)
