### ISSUE TITLE
Compiler configuration could support not only paths but https URLs (V5)

### ISSUE THREAD

**Issue by axic** [trufflesuite/truffle#1274]
According to the [0.5.0 release notes](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0) there are different ways to select a compiler version.

Using a version number
```
  solc: {
    version: "0.4.22",
  }
```
only seems to work with releases, and `truffle compile --list --all` also only lists them.

It would be nice to support nightly releases (in some cases), though it may be a bad idea supporting that easily via the above feature.

However, truffle also supports specifying a path, such as `version: "/home/test/mycompiler.js"`, which I think could be extended to be a URL:
- `file:///home/test/mycompiler.js`
- `https://solc-bin.ethereum.org/bin/soljson-v0.4.26-nightly.2018.9.13+commit.8b089cc8.js`

In this case it could be used for nightlies and specific compiler versions (such as one with Z3 included), yet it requires a bit more work from the user compared to just dropping in a number and as a result should discourage randomly selecting a prerelease.

**Comment by gnidan** [comment]
From conversation with @axic offline: there might also be an issue with how CompilerSupplier is wrapping `soljson`. It seems that truffle-compile is not working correctly with raw `soljson` values, and instead only works with the full `solcjs` pre-built wrapper.

This should not be necessary because of the `solcWrap` functionality in that package (invoked [here](https://github.com/trufflesuite/truffle/blob/next/packages/truffle-compile/compilerSupplier.js#L411), definition [here](https://github.com/trufflesuite/truffle/blob/next/packages/truffle-compile/solcWrap.js)).

Beyond that, it might be possible to use the wrapping functionality provided by `solcjs` natively, by calling `require('solc/wrapper')(require('/path/to/soljson'))`, although this might not work within the confines of the bundled version of Truffle. (@cgewecke would know why the `solcWrap` file exists in the first place.)

[This project](https://github.com/ewasm/sentinel-governance) has a Truffle project set up with the config pointing to the desired `soljson` URL (`https://`). This config is not working, and instead [this branch](https://github.com/ewasm/sentinel-governance/tree/truffle-workaround) has a workaround.

**Comment by cgewecke** [comment]
@axic @gnidan 

Not sure if this is helpful but it *is* currently possible to get a list of nightlies and to pull one from solc-bin:
```shell
truffle compile --list prereleases --all
[
 ...
 "0.4.25-nightly.2018.9.10+commit.86d85025",
 "0.4.25-nightly.2018.9.11+commit.d66e956a",
 "0.4.25-nightly.2018.9.12+commit.9214c7c3",
 "0.4.25-nightly.2018.9.13+commit.15c8c0d2",
 "0.4.26-nightly.2018.9.13+commit.8b089cc8",
 "0.4.26-nightly.2018.9.17+commit.2409986c",
 "0.4.26-nightly.2018.9.18+commit.fcb48bce"
]
```
Tests for that [here](https://github.com/trufflesuite/truffle/blob/next/packages/truffle-compile/test/test_supplier.js#L127-L143). 

`getByUrl` assumes you'll a version string (like the ones above) and the Supplier manages the url path construction.

`solcWrap` is borrowed from the solc module and provides the correct interface to npm `require` because versions published to solc-bin target a browser-based environment (like remix). The wrap was broken out like this in the hope of avoiding a full `require('solc')` statement just to access it. When [profiling the supplier](https://github.com/trufflesuite/truffle-compile/pull/67) it looked like that statement on its own takes > 1 second to execute.

**Comment by axic** [comment]
~~I could have sworn I have tried this yesterday and it didn't list preleases.~~

I see what the problem was, tried `--list --preleases`. It seems to be working with `compile` too.

I have two suggestions:
- add an some progress indicator when soljson is being downloaded the first time (I see it caches it after)
- improve the release notes / documentation about using prereleases

This issue can be closed otherwise.

**Comment by cgewecke** [comment]
> add some progress indicator when soljson is being downloaded the first time (I see it caches it after)

Yes completely agree - we have this open at #1132. 

> improve the release notes / documentation about using prereleases

This command is documented in the release notes, but maybe we should have good examples for all the possibilities in the config as well. There's also ongoing work on #1262 which will looks like it will improve the help command a lot as well.
