### ISSUE TITLE
Update solc to 0.4.25

### ISSUE THREAD

**Issue by rjkz808** [trufflesuite/truffle#1292]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

There's a new solidity compiler version

**Comment by H34D** [comment]
closes with #1277

**Comment by gnidan** [comment]
Closing!

**Comment by celeduc** [comment]
Why, why, _why_ does Truffle persist in hard-coding the solc version? Allowing users to manage this dependency would allow us to upgrade solc to avoid dangerous compiler errors as they arise without maintaining our own fork.  It would be as simple as putting `"solc": "^0.4.25"` instead of `"solc": "0.4.25"` in the package.json.

**Comment by gnidan** [comment]
@celeduc Truffle does not persist in hard-coding the solc version. The hard-coded there is now to serve as a convenient default. See the Truffle v5.0.0-beta.0 release notes: https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#bring-your-own-compiler

**Comment by celeduc** [comment]
@gnidan Thanks, I appreciate the tip. TFM is excellent :+1:
