### ISSUE TITLE
installing truffle@next vs truffle@beta

### ISSUE THREAD

**Issue by RobertoC27** [trufflesuite/truffle#1443]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Noticed that when current releases(5.0) suggest installation with truffle@beta. When darq-truffle became truffle@next i was told to use it. But now that both truffle@next and truffle@beta produce a valid installation which one should I use.

@cgewecke any chance you could shed some light on this?

**Comment by gnidan** [comment]
We use `truffle@beta` for mostly-stable product releases, which include full changelog + release notes. We plan these ahead of time and do our best to ensure everything works as best we can. Beta releases are not entirely stable, but bugs found in them are usually a higher priority for us to fix.

On the other hand, `truffle@next` is more akin to a "nightly", or a development release. It represents a release in progress, containing the latest and greatest. This is much more likely to be broken, but it's handy because it allows users to try out new features or bug fixes before the scheduled release.
