### ISSUE TITLE
package:truffle-hdwallet-provider pin dependencies

### ISSUE THREAD

**Issue by flockonus** [trufflesuite/truffle#1536]
## Issue

This package is a big service to the community, and hugely important for many deployment flows.
But it also bears the responsibility of holding private keys, and as such it would be better off with pinned dependencies, a package-lock.json and yarn.lock file, given the recent attacks to npm dependencies.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

Fixed dependencies

**Comment by gnidan** [comment]
Hello, nice to see you here!

Now that hdwallet-provider is in the monorepo, it uses the `yarn.lock` that's in the root. We are also now webpacking hdwallet-provider so that most dependencies are even more locked, cause they make it into the bundle completely.

I think the only work left here is to pin the dependencies.

**Comment by flockonus** [comment]
Cool! Indeed it's most of the way through.

My original concern was about ppl like me installing `truffle-hdwallet-provider` from npm or yarn. I don't think yarn.lock on the root of the monorepo relevant for this purpose.

Would you happen to know exactly how those 2 package managers pull dependencies of dependencies? I'd expect it to obey a package-lock.json if that is present in the package 🤔
