### ISSUE TITLE
Accommodate broken support for Quorum/other chains via `--legacy` flags to use old code

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1543]
Discovered by @CruzMolina and @EdsonAlcala: Quorum support in Truffle seems to be broken with the new migrations system.

This is most directly observed in the failing `web3.eth.getBlock()` call on [this line](https://github.com/trufflesuite/truffle/blob/next/packages/truffle-migrate/migration.js#L186), where web3.js fails to decode the blog gas limit due to a web3-internal `bn.toNumber()` call (`Error: Number can only safely store up to 53 bits`), but there may be other problems.

As a last-minute effort to maintain Quorum support, @CruzMolina has proposed the idea of a legacy system, to take the code on `develop` and wire it up as an alternative for `truffle migrate` and `truffle test`.

**Comment by melnikaite** [comment]
Have a look at this approach https://stackoverflow.com/a/54595252/1099933

**Comment by seesemichaelj** [comment]
Thanks @melnikaite for the suggestion! The approach taken in #1544 to support this issue covers other potential vectors where the "old" version of web3 (`0.20.x`) is needed than just this specific case with Quorum

With that said, your approach may come in handy with some future work around this issue, and we'll keep it in mind! Thanks again!

**Comment by seesemichaelj** [comment]
#1806 fixes this issue. The original issue was due to large timestamps, not large gas limits (#1809 addresses large gas limits).

This will go into the next release of Truffle. The fix addressed here will now let you use Truffle v5 with the Quorum tutorial found [here](https://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains).

The documentation on the above tutorial and the [official docs](https://truffleframework.com/docs) will be updated before the release.

Going forward, you'll be able to specify `type: "quorum"` in your `truffle(-config)?.js` network, like such:
```
...,
networks: {
  development: {
    type: "quorum",
    ...
  }
}
```

**Comment by seesemichaelj** [comment]
This has been released in https://github.com/trufflesuite/truffle/releases/tag/v5.0.9

**Comment by seesemichaelj** [comment]
Please let us know if you have any issues or questions! You can [read documentation on the necessary changes to use Quorum here](https://truffleframework.com/docs/truffle/getting-started/working-with-quorum).
