### ISSUE TITLE
truffle compile/migrate fail to build, no error output

### ISSUE THREAD

**Issue by mcgingras** [trufflesuite/truffle#1703]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
no, but I was instructed to open an issue on twitter.
---------------------------

## Issue

Truffle compile and truffle migrate are both failing to build, or do anything for that matter.

## Steps to Reproduce

In a new directory...
truffle init
create a basic contract
create migrations
ganache-cli -b 3
truffle compile

## Expected Behavior

typically truffle compile will build the contracts for you

## Actual Results

Nothing happens, not even error messages. The terminal spins for a bit then returns.

## Environment

* Operating System: High Sierra 10.13.6
* Ethereum client: ganache
* Truffle version (`truffle version`): 5.0.3
* node version (`node --version`): 10.13.0
* npm version (`npm --version`): 6.4.1

**Comment by hayesgm** [comment]
This may be unrelated, but I recently had a similar issue that had to do with maximum stack depth (though it wasn't being reported). My fix was simply running:

`node --stack_size=2000 "./node_modules/truffle/build/cli.bundled.js" compile`

**Comment by mcgingras** [comment]
That work perfectly! Thanks so much.

**Comment by FlashBlaze** [comment]
I know this issue is closed, but I was able to solve it by running compile and migrate as a root. You can close this if you want, but I just wanted to put it out there.

**Comment by AtlasQuan** [comment]
I successfully sovle it by the way @FlashBlaze referred to. 
Just a comment, I guess the reason why this promblem appear is because at the beginning, the truffle was installed by sudo persmission. Then when you use the regular user permission, this problem will happen.
(Honestly, I believe except using root permission, there's supposed to be more 'beautiful' solutions. But I havn't known yet.)
But I could be wrong. Welcome to your criticism.

**Comment by jainsuchita** [comment]
Thank you @AtlasQuan Worked for me.

`sudo truffle compile`
