### ISSUE TITLE
2 versions of mocha in package.json

### ISSUE THREAD

**Issue by WyseNynja** [trufflesuite/truffle#1705]
https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/package.json#L8 has ` "^4.1.0",`

https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/package.json#L25 has `"5.2.0",`

Is this intentional? It seems odd to have two versions defined in package.json.

**Comment by gnidan** [comment]
One of the mochas is for Truffle's internal test suite and the other for `truffle test`.

I've been hesitant to bother remedying this, mostly because:
- `truffle test` has a lot of legacy code, so it's risky to upgrade mocha with breaking changes
- lack of urgency (I don't remember many other mentions of this discrepancy). 
- the plan is to generalize `truffle test` to support any framework on the order of "pretty soon", so it has appeared to be a naturally temporary problem

But, it might be trivially easy to do the upgrade, and my reasoning thus unsound. Or just plain invalid for reasons I'm missing. Either way, my attempts at judicious laziness aside, I would prefer these versions be in sync!

If you feel like taking a stab at this, I'd be happy to help sort out any trickiness you encounter in a PR.

**Comment by WyseNynja** [comment]
Which mocha is used for which test suite?

Mocha's CHANGELOG looks like it has good documentation for breaking changes. The only breaking change for 4 to 5 is about dropping support for IE9 and IE10 which I think is unlikely to break truffle.  Upgrading up to mocha 6 has more breaking changes listed.

https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-change's

I'll test this change against my project and see what happens.

**Comment by boolafish** [comment]
To upvote this issue, it seems like mocha 4 has a dependency (`diff`) that might have security issue and need to be updated:
https://snyk.io/node-js/mocha

We are getting GitHub security alert because having truffle as dependency.
https://github.com/omisego/plasma-contracts/network/alert/package-lock.json/diff/open
```
└─┬ truffle@5.0.21
  └─┬ mocha@4.1.0
    └── diff@3.3.1
```

**Comment by eggplantzzz** [comment]
It looks like version 4 of mocha was removed from the dev dependencies section of truffle. I believe that this issue can be closed...?

**Comment by haltman-at** [comment]
This seems to have been fixed long ago, closing.
