### ISSUE TITLE
Add support for mocha-parallel-tests

### ISSUE THREAD

**Issue by PhABC** [trufflesuite/truffle#1707]
It would be great if truffle could add a flag (or make it as a default) such that tests can be executed in parallel, perhaps via https://www.npmjs.com/package/mocha-parallel-tests 

There might be  need to run multiple ganache / nodes instances in parallel as well to make sure there are no transaction nonce conflicts, but maybe a ganache fork could also work. 

Running tests in parallel could drastically reduce testing times, which in many cases can take a while.

**Comment by gnidan** [comment]
This would be great! But it's tricky and would constitute a breaking change, were it to be default. Have you tried configuring Mocha via Truffle's config (see docs [here](https://www.truffleframework.com/docs/truffle/reference/configuration#mocha))? It might work that way, without a change to Truffle itself.

**Comment by kkx** [comment]
@gnidan 
The config used in truffle-config is for configuring mocha itself, there is no way to change using other enchanced mocha library instead of the standard mocha.
would be great if user can select the mocha library to use and import it dynamically when creating Mocha instance here in this line:
https://github.com/trufflesuite/truffle/blob/b4b26add0239bb89da0aa562e730023d5eb35341/packages/core/lib/test.js#L124

like this:
```
// mocha-parallel-tests example
// if you're using TypeScript you don't need to install @types/mocha-parallel-tests
// because package comes with typings in it
import Mocha from 'mocha-parallel-tests'; // or `const Mocha = require('mocha-parallel-tests').default` if you're using CommonJS
const mocha = new Mocha();
```

**Comment by gnidan** [comment]
Sure @kkx I think that can work by adding a field to the `mocha` part of the Truffle config: https://www.trufflesuite.com/docs/truffle/reference/configuration#mocha

Feel free to open a PR for this and we can make sure it won't break anything. Seems straightforward though... good idea!

**Comment by k06a** [comment]
@kkx any chance you will contribute this?

**Comment by k06a** [comment]
This is my try: https://github.com/trufflesuite/truffle/pull/2540

**Comment by eggplantzzz** [comment]
Merged in Truffle [v5.1.11](https://github.com/trufflesuite/truffle/releases/tag/v5.1.11)

**Comment by mrice32** [comment]
Should this be reopened? Parallel tests seem to only be supported in principle. They are not supported in practice due to the issue raised [here](https://github.com/trufflesuite/truffle/pull/2540#issuecomment-585804084). Is there any way to get artifacts to work in this context? Otherwise, this feature isn't usable (as far as I can tell).

**Comment by leovigna** [comment]
I've been able to run parallel smart contract tests but as mentioned in the comment you linked, one has to overcome the limitations posed by truffle's globals.
Here are the steps I took to enable parallel mocha tests.
### Install required packages
* `npm install -D ganache-core`: We will use this to spawn a separate ganache-core per process. This avoids nonce conflicts and reduces IO bottlenecks. Even in the non-parallelized tests I've found some speedup by using ganache-core as provider instead of server. https://github.com/trufflesuite/ganache-cli#options
* `npm install -D @truffle/contract`: We use this to bypass the artifacts global and create our own contracts.
### Remove Globals
We first have to remove references to all Truffle globals `contract()`, `assert()`, `artifacts` and replace these with substitutes.
* `contract()` replaced with mocha `describe()`. You must also replace `(accounts) => { ... }` with `() => { ... }` 
* `assert()` fixed by adding missing import `import assert from 'assert'`
* `artifacts` this is the trickiest to replace.Use the `@truffle/contract` package to create the contracts manually. You can do this for each test file but it's simpler to just have a separate `artifacts.ts` file from which tests import. We use the build output to create the contract and connect it to the ganache provider.
```typescript
import TestTokenArtifact from "../build/contracts/TestToken.json"

const Contract = require("@truffle/contract");
const TestToken = Contract(TestTokenArtifact)
const provider = ganache.provider()
TestToken.setProvider(provider)

export {
    TestToken
}
```
Now you can import the contract in your test file.
```typescript
import { TestToken } from "../../artifacts"
```
If you wish to preserve backwards compatibility with the artifacts interface you can also add this to the `artifacts.ts`:
```typescript
const contracts = {
    "TestToken": TestToken
}

//patch mock artifacts object for backwards-compatibility
const artifacts: Truffle.Artifacts = {
    require(name: string) {
        //@ts-ignore
        return contracts[name]
    }
}

export {
    artifacts,
    TestToken
}
```

### Configure Accounts
Recall we lost access to the accounts list provided from the `contract()` test function. Add the following to the `artifacts.ts` file.  
```typescript
let accounts: string[]
let configured = false

async function configureAccounts() {
    if (!configured) {
        accounts = await web3.eth.getAccounts()
        for (let k in contracts) {
            //@ts-ignore
            contracts[k].web3.eth.defaultAccount = accounts[0]
        }

        configured = true
    }
}
export {
    accounts...
}
```
In your test files, import accounts and add a `before()` hook:
```typescript
import { accounts, configureAccounts } from "../artifacts"

//contract('TestToken', function (accounts) {  //incompatible with mocha parrallel
describe('TestToken', function () {
    before(async () => {
        await configureAccounts()
    })
})
```

### Configure Mocha
Edit your `truffle-config.json`. We turn on the parallel flag and increase timeout (individual tests can take more time depending on how they are scheduled on the CPU).
```typescript
module.exports =  {
  //...
  mocha: {
        parallel: true,
        timeout: 300000 //5min
    }
}
```
### Conclusion
Mocha spawns processes on a per-file basis so you will only experience performance improvements if your test suite includes multiple long-running tests in separate files. You will also be limited by the number of CPU cores you have. This post by IBM goes through the details of how it works https://developer.ibm.com/languages/node-js/articles/parallel-tests-mocha-v8/.

In my case I had 5 test files. Initially ran in 4min which I was able to bring down to 50sec with this method. Exactly the 5x improvement you'd expect assuming you had the CPU cores.

How could parallel tests be enabled by default with truffle? I think clearly the long-term solution would be to enable a functional way to generate/import `artifacts`, `contract()` and have it all be configured in a process spawned by mocha. Maybe this is already possible but not well documented? I'm not familiar enough with the full truffle suite to know where changes would be necessary.

All the patched I've listed above are basically just removing globals and having them be created on a per-process basis. While this adds some slight overhead (eg. 1 artifact per process) this is insignificant compared to the speedup achieved by parallelized tests.

Note: All tests are in Typescript so you might also have to configure that or adapt the imports if using Javascript.
