### ISSUE TITLE
Error Not compatible with your OS

### ISSUE THREAD

**Issue by kingvinay110** [trufflesuite/truffle#1848]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes
## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System:  Ubuntu 18.04.02
* Ethereum client:
* Truffle version (`truffle version`): 4.1.13
* node version (`node --version`): 8.10.0
* npm version (`npm --version`):  3.5.2

![VirtualBox_Ubuntu_22_03_2019_15_00_13](https://user-images.githubusercontent.com/48646228/54813299-3bf0bb00-4cb3-11e9-9d8b-287b7e8ae8f9.png)

**Comment by gnidan** [comment]
Looks like you're several versions behind. If you want to stick with Truffle v4, you'll want v4.1.15.

But of course we recommend you upgrade to the latest v5.0.9 :)

Closing this, since I don't believe there's a bug, but feel free to comment and I'll happily re-open. Let us know if upgrading works! Thanks!
