### ISSUE TITLE
Reduce barrier to entry for new users

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#205]
Part of solving the PR problem:
- [x] Remove default build process (it's overwhelming, potentially)
- [x] Add examples for many different types of build processes and scenarios: webpack, javascript library, console dapp, browserify, React, Angular? 
- [x] `truffle init` should allow for people to choose the above options. Maybe have documentation similar to babel? https://babeljs.io/docs/setup/
- [x] The above implies a website dedicated to Truffle 
- [ ] Use TestRPC by default for `truffle test`. Users can override this behavior by saying `truffle test --network xxx`

Note that development tasks are very intertwined with _effective communication_.

**Comment by nemild** [comment]
OSS and effective communication are always tied together, for getting feedback, recruiting devs, driving usage, making sure onboarding is easy, etc. Otherwise, it's really hard to get good feedback loops and get contributors/users.

I like the idea of making it easy to slot in any build process or frontend framework - there are a ton of projects that track what is acceptable in diff ecosystems (gulp vs webpack, react vs angular), so I think it's a good idea to offload the work on maintaining this to another repo and focus on the contract environment, which is a pretty involved job on its own.

Also, I know it might be a nice to have the Babel JS type page, but they have a lot of contributors. In the early days, it might be easy to pick 1-2 for specific examples and then give some generic examples of how to slot any others in - motivated users can always add in their framework of choice to your documentation.
