### ISSUE TITLE
contract.method.request() doesn't work and isn't very useful even if it did

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#2293]
## Issue

This is something of a continuation of issue #381; not the original issue, mind you, but the issue raised below in the comments -- that as of Truffle v5, `contract.method.request()` no longer works.

What I want to point out here is that, in addition to no longer working, the [intended] return value of `contract.method.request()` is not really as useful as it could be.

As best I can tell, the intended return value of `contract.method.request()` is that it's supposed to be the JSON for an RPC call (I'm assuming one that would send that transaction).  I think it would be much more useful if it returned a corresponding web3 transaction object instead.

Reasons:

1. A JSON RPC object is specific to a specific method, whereas a web3 transaction object could be used for any of `sendTransaction`, `call`, or `estimateGas`.

2. A web3 transaction object can easily be used with the widely-used web3 library, while using a JSON RPC requires doing one's own RPC calls.

3. A JSON RPC object just contains a bunch of irrelevant information that most people won't want.

4. ~~Continuing on the theme of (1), doing `request` this way would allow `sendTransaction`, `call`, and `estimateGas` to later be reimplemented as mostly wrappers around `request`, putting all the heavy lifting in one place, namely `request`.~~ Nevermind, this is what `prepare` does.

Now, ordinarily, changing this behavior would be a breaking change... but seeing as `request` hasn't properly worked since Truffle v4 anyway, perhaps that's OK in this case?

Anyway, I would like to suggest that:

1. The `request` method be fixed, and

2. Its return value be altered as above.

**Edit**: I would also like to suggest that, as long as we're sort-of breaking things, perhaps its name could be changed to something more fitting.  Not sure what that would be, though.  ~~I was thinking perhaps `prepare`, but not sure that's clear enough, and that might be potentially confused with other things?~~  OK, see comment below.  What I'm describing is really what `prepare` does, so really we should just expose that instead of this.

**Comment by haltman-at** [comment]
Oh I guess actually `prepare` is exactly this, oops?  Yeah so IMO instead of fixing `request` it would make more sense to just expose `prepare`.

**Comment by haltman-at** [comment]
Although maybe `prepare` doesn't do what I think it does.  Anyway the point is what we should expose is what I described above, whether that's what `prepare` does or not.

**Comment by CruzMolina** [comment]
Did some sleuthing a while back and it turns out `contract.method.request(params)` is not only super old, but also commented out in the [0.2x.x docs](https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-methods)!

It also appears it was deprecated at some version of Web3.js 0.2x.x in favor of `contract.method.getData(params)`, which returns a bytestring. It's quite possible that `request` always returned a bytestring.

Furthermore, it looks like `getData` didn't make it into Web3.js 1.x and got replaced by... [`contract.methods.method(params).encodeABI()`](https://web3js.readthedocs.io/en/v1.2.4/web3-eth-contract.html#methods-mymethod-encodeabi), which also returns a bytestring.

Since this method already doesn't work and is not documented, I'm sure no one is really using or relying on it. Having whatever this future method becomes return a web3 tx object (while we still bundle web3), seems like a good idea!
