### ISSUE TITLE
Truffle install <ethPM package> failing 

### ISSUE THREAD

**Issue by KadenZipfel** [trufflesuite/truffle#2528]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to install ethPM packages with truffle install is not working. Initially I tried it on v5.0.42 and received the error `Error: Returned values aren't valid, did it run Out of Gas?`, then I tried rolling back to v5.0.19 and now I'm getting `Error: Cannot find any published versions of 'ds-math' with the specified version range (*)`.

## Steps to Reproduce

In a truffle box, run `truffle install ds-math`.

## Expected Behavior

It should install the ethPM package without error.

## Actual Results

It's returning errors as noted above.

## Environment

* Operating System: Windows
* Ethereum client: Geth
* Truffle version (`truffle version`): v5.0.42 & v5.0.19
* node version (`node --version`): v10.16.3
* npm version (`npm --version`): v6.9.0

**Comment by eggplantzzz** [comment]
Thanks for reporting this! We will look into it

**Comment by Leocn** [comment]
same issue.
return code 
`Error: Returned values aren't valid, did it run Out of Gas?`

Truffle v5.0.34 (core: 5.0.34)
Solidity v0.5.8 (solc-js)
Node v10.16.3
Web3.js v1.2.1
npm v6.9.0

**Comment by eggplantzzz** [comment]
The last version I can find where this worked is `5.0.8`.

**Comment by eggplantzzz** [comment]
Actually it looks like it works with openzeppelin. Try doing `truffle install zeppelin`. For me it is successful, there must be something particular about `ds-math` that is causing it to fail.

**Comment by savil** [comment]
hmm `sai` also doesn't work (but perhaps that is related to `ds-math` as well, since both are from makerdao).

Prior to truffle 5.0.32 (if i recall correctly), the error is: `Cannot find any published versions of 'sai' with the specified version range (*)`. Note: adding a valid version number (`1.0.0`) doesn't help :)
Stack trace: https://gist.github.com/savil/d11f54e5598f873652f83c576b98c27c


and after truffle v5.0.33, the error is: `Returned values aren't valid, did it run Out of Gas?`
stack trace: https://gist.github.com/savil/4fecdf8f3ff09b238f441addc579924a

**Comment by eggplantzzz** [comment]
Since `zeppelin` does work and the others don't I'm going to close assuming that it is not a problem on Truffle's side. If you can verify that it is indeed a Truffle problem, we can definitely re-open it! Thanks.
