### ISSUE TITLE
Make Debugger show reject message

### ISSUE THREAD

**Issue by MicahZoltu** [trufflesuite/truffle#2551]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
When using Truffle Debugger to debug a contract call rejection without source maps available, the debugger does not show you the rejection message.

## Steps to Reproduce
Debug a contract without source maps.

## Expected Behavior
See the rejection message even if source maps are unavailable for the transaction being debugged.

## Actual Results
Just a "reject" with no message.

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache
* Truffle version (`truffle version`): 5.0.x
* node version (`node --version`): v12.3.0
* npm version (`npm --version`): 6.9.0

**Comment by gnidan** [comment]
cc @haltman-at

**Comment by haltman-at** [comment]
Huh, that's odd.  I'm afraid I'm currently quite busy preparing for the 5.1 release, but as soon as that's out of the way I'll take a look at this first thing.  Thanks for reporting this!

**Comment by haltman-at** [comment]
Ah, I see -- this is a feature request, not a bug report.  The description was a misleading here; it made it sound like it *does* determine a reason string when there is source, but not when there isn't.  When in fact, it does not determine a a reason string regardless.  It's just that, if there's source, you can often determine the reason string anyway by stepping through to the end.

OK.  So you want us to determine (and display) the reason string in case of a revert.  Since that's a new feature rather than a bugfix I might not get to it immediately, but it does mesh nicely with some other things I was planning on doing, so I should get to this pretty soon.  Thanks for bringing this up!

**Comment by haltman-at** [comment]
OK, I've created PR #2662 to address this.

**Comment by haltman-at** [comment]
Oops, looks like this was never closed.
