### ISSUE TITLE
Compile contracts from npm

### ISSUE THREAD

**Issue by ilanolkies** [trufflesuite/truffle#2611]
# Issue

I use contracts from an npm package. When running tests without migrations I use this trick to make npm contracts code appear in build/contracts and deploy them using `artifacts.require`. 

https://github.com/ensdomains/resolvers/blob/master/test/mocks/dummy.sol

## Steps to Reproduce

1. Import an npm package with a smart contract
    ```
    truffle init
    npm i @ensdomains/ens
    ```
2. Add `artifacts.require('@ensdomains/ens/ENSRegistry')` in a new test
3. `truffle test`

## Expected Behavior

Work! Find the npm contract in build, without adding that patch

* Operating System: macos, ubuntu (in circleci)
* Ethereum client: truffle develop
* Truffle version (`truffle version`): latest
* node version (`node --version`): latest
* npm version (`npm --version`): latest

**Comment by fainashalts** [comment]
HI @ilanolkies thank you for bringing this to our attention! Can you clarify, is the issue that `artifacts.require()` is not working in this case?  

Can you take a look at issue #2612 and let us know if that issue is the same thing? If it is different, can you make a test repo for us to reproduce this issue from? Thanks!

**Comment by ilanolkies** [comment]
That issue has a great idea! Contracts should be deployed with the provided bytecode. That bytecode could be audited.

> Use the files from node_modules/<package>/build if they exist, instead of recompiling all contracts.

I'll close this. Thanks.
