### ISSUE TITLE
hey just needed a small help. I have built a blockchain dapp, a simple one which just has a user form and accepts some data. I want to host it on any cloud platform, how to do it? please help

### ISSUE THREAD

**Issue by Unmesha1** [trufflesuite/truffle#2622]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by fainashalts** [comment]
Hi @Unmesha1, thanks for reaching out about this! Since this isn't a bug or a feature request, you may be better served by asking other DApp developers about this. Some good resources are ethereum.stackexchange.com and reddit.com/r/ethdev, as well as the Truffle gitter.com/consensys/truffle where someone may be able to point in the right direction. Closing for issue maintenance, but I hope that helps!
