### ISSUE TITLE
Test Isolation in Truffle 5.1.5

### ISSUE THREAD

**Issue by mrice32** [trufflesuite/truffle#2710]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I think truffle 5.1.5 broke test file isolation.

The same contract addresses seem to be used across multiple test files when running `$(npm bin)/truffle test`. From a deeper investigation, it looks like a fresh migration is occurring, but the addresses that are injected into the environment aren't being updated from test to test.

## Steps to Reproduce

See https://github.com/mrice32/truffle_example for a simple example (varies only slightly from `truffle init`) of the test isolation issue.

```
git clone https://github.com/mrice32/truffle_example
cd truffle_example
npm install
$(npm bin)/truffle test
```

## Expected Behavior

Tests should pass and print different addresses.

## Actual Results

Output for `$(npm bin)/truffle test` in the above repository.
```

Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol



  Contract: 1
0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0
    ✓ Check and Set value (69ms)

  Contract: 2
0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0
    1) Check and Set value
    > No events were emitted


  1 passing (271ms)
  1 failing

  1) Contract: 2
       Check and Set value:

      AssertionError: expected '1' to equal '0'
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (test/2.js:7:12)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

## Environment

* Operating System: Mac OS X 10.15
* Ethereum client: Default truffle test client
* Truffle version (`truffle version`): Truffle v5.1.5
* node version (`node --version`): v11.15.0
* npm version (`npm --version`): 6.13.4

**Comment by haltman-at** [comment]
OK, it looks like what happened here is that I accidentally broke the logic used to detect if we can use snapshots to revert the state.  So, instead of reverting via snapshot like would've happened prior to 5.1.5, instead a redeploy is happening (the fallback used if snapshots aren't available).  I think I exposed an underlying bug in that.

Anyway, I'm just going to try to fix the snapshot logic so it goes back to using snapshots.  I don't know what to do about the underlying redeploy bug; I'll probably just open an issue for that after fixing this so that we're aware of it for the future.

**Comment by haltman-at** [comment]
OK, I've put up PR #2727 to fix this.  Or at least to fix the immediate problem; I have no idea what to do about the underlying bug that got exposed, but things will at least be back to working how they were before.
