### ISSUE TITLE
"Migrations" -- transaction's gas price lower than block's minimum.

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [trufflesuite/truffle#2738]
I get **"Migrations" -- transaction's gas price lower than block's minimum.** when running `truffle migrate --reset`

```javascript
require('babel-register');
require('babel-polyfill');
var HDWalletProvider = require('@truffle/hdwallet-provider')

var mnemonic = 'mnemonic code'
var publicNode = 'https://public-node.testnet.rsk.co:443'

module.exports = {
  networks: {
    // development: {
    //   host: "127.0.0.1",
    //   port: 7545,
    //   // gasPrice: "30000000000",
    //   network_id: "*" // Match any network id
    // },
    
    rsk: {
      provider: () =>
      new HDWalletProvider(mnemonic, publicNode),
      network_id: '*',
      // gas: 25000000,
      gas:4600000,
      gasPrice: 6800000
    }
  },
  contracts_directory: './src/contracts/',
  contracts_build_directory: './src/abis/',
  compilers: {
    solc: {
      optimizer: {
        enabled: true,
        runs: 200
      },
      evmVersion: "byzantium"
    }
  }
}

```

**Comment by gnidan** [comment]
Hi @GoodnessEzeokafor - since you're using RSK, you might want to check out their docs to see how they recommend configuring this. You could try upping the `gasPrice` value and see if that helps.

I also hear that there will soon be example RSK boxes that you will be able to use for reference.

Closing this since this isn't likely a bug. Happy to continue the discussion on [our Spectrum channel](https://spectrum.chat/trufflesuite?tab=posts)! Thanks!
