### ISSUE TITLE
Truffle Script halts in a loop

### ISSUE THREAD

**Issue by alexy97** [trufflesuite/truffle#2878]
I am trying to run a very simple script using the truffle exec command  which sends a bunch of transactions to the node. I am not using await on the method calls , but the execution still wait and does not proceed which results in only 1 iteration. 

```javascript
const EnergyToken = artifacts.require("EnergyToken");


module.exports = async   function(callback) {
  fetch();
  console.log("Sending transactions...");
  const contract =  await 
  EnergyToken.at("0x9cF19b3215C4dEa492F7609425f5A230DCD13DE9"); 
   
  for (let cnt = 1; cnt <= 50; cnt++ {
      console.log("Transaction " + cnt);
      contract.transfer(accounts[1],cnt);
  }
    console.log("Successfully sent transactions!");
    callback();
}
```
I am not sure if this is expected behaviour or if there is some kind of workaround but for my test I need to send the transactions without waiting for each response individually.

**Comment by eggplantzzz** [comment]
So the fact that `contract.transfer` is an asynchronous function is probably what is causing your problem. The loop is synchronous and it calls `transfer` each time. However, it does not wait for the function to finish, jumps out of the loop, and calls the callback. This, in turn, probably exits the process and thus does not deal with whatever happens when the data comes back. So maybe just `await` each `contract.transfer` if you want to make sure you completed all calls. I hope this helps!

**Comment by eggplantzzz** [comment]
Closing as this is probably not an issue with Truffle. If you find it actually is a problem, get back to us and we'll be happy to re-open it!
