### ISSUE TITLE
Unable to get a revert reason when testing smart contract using Truffle against a GETH node.

### ISSUE THREAD

**Issue by Jaime-Iglesias** [trufflesuite/truffle#3105]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Unable to get a revert reason when testing smart contract using Truffle against a GETH node.

Let's say I have the following contract

```Solidity
contract Foo { 
 function foo(uint256 a, uint256 b) external pure returns (uint256) {
        require(a < b, "some message");

        return a + b;
 }
}
```

With the following test running on Truffle (using HDWalletProvider) :

```js
const Foo = artifacts.require('Foo');

contract('Foo', function () {
  beforeEach(async function () {
        this.foo = await Foo.new();
  });

  describe('foo', function () {
     context('when a is not lower than b', function () {
       const a = new BN('1');
       const b = new BN('0');

       it('reverts', async function () {
            const res = await this.calculator.foo(a, b);
            // this returns  BN 8c379a00000000000000000000000000000000000
            // for those who do not know, 8c379a is what Solidity prefixes an error reason with.
            // but for truffle this is not reverting, it's just returning a result as if the transaction was a success
            // interestingly enough, I have managed to retrieve revert reasons out of other unit tests against the same GETH node
       });
     });
  });
});
```

with this alternative test running on Mocha:

```js
const Web3 = require('web3');

const Foo = require('path/to/Foo');

const web3 = new Web3('localhost:port');
web3.eth.handleRevert = true;

describe('Foo', function () {
  beforeEach(async function () {
        var contract = new web3.eth.Contract(Foo.abi);
        this.foo = await contract.deploy({ data : contract.bytecode }).send({ gas: gas, from: accounts[0] });
  });

  describe('foo', function () {
     context('when a is not lower than b', function () {
       const a = new BN('1');
       const b = new BN('0');

       it('reverts', async function () {
            try { 
               await this.calculator.methods.foo(a, b).send({ gas: gas, from: accounts[0] });
            } catch (err) {
                 console.log(err.reason);
                  // this logs the expected revert message
            }
       });
     });
  });
});
```
## Steps to Reproduce

- Run the above test cases against a local GETH node
- latest version of truffle you can get from npm.
- latest version of web3 (on the pure web3 tests).

## Expected Behavior

That truffle recognizes that the transaction is reverting and returns the revert message.

I have to clarify that I have tried researching if this is a GETH problem (i.e if GETH actually supports revert reasons) and I have found contradicting answers (based on issues and PRs) what also makes it weirder is the fact that I have managed to get revert reasons out of other unit tests and that I can use pure web3 to retrieve the revert reason.

Also, it's worth noting that everything works as expected against a ganache-cli instance.
## Actual Results

it returns a BN value `8c379a00000000000000000000000000000000000` representing Solidity's encoding of a revert (not even a string message or something similar that makes it obvious)

## Environment

- Run the above test cases against a local GETH node
- latest version of truffle you can get from npm.
- latest version of web3 (on the pure web3 tests).
- node v10.19.0

**Comment by Jaime-Iglesias** [comment]
So, after some extra testing my conclusion is that this is due to GETH not suporting revert reasons yet - I might be wrong on this and it might be an issue on the Truffle side but I haven't been able to identify what's happening.

**Comment by haltman-at** [comment]
I can explain what's going on here.  I won't reopen this unless you think it should be reopened, but I can certainly explain what's going on here.

So, before I go on, I should say, there is a quick workaround for your problem.  Your problem is occurring because `foo` is a `pure` function, and therefore, by default, when you do `calculator.foo(a, b)`, Truffle defaults to performing a call rather than a transaction.  However, you can do `calculator.foo.sendTransaction(a, b)` in order to force it to make an actual transaction.  If you do this, you should get the exception you expect.

Now then: Why is this happening?

First, I should note that this doesn't really have to do with revert *reasons*.  Rather it has to do with, do reverts cause exceptions?  In web3, reverts cause exceptions, and Truffle (which uses web3) preserves this behavior.  But when we say "reverts cause exceptions", this really means "reverting *transactions* cause exceptions".  Reverting calls do not cause exceptions in web3... usually.  I'll talk about an exception to this in a bit.

So why don't reverting calls cause exceptions in web3?  Well, it comes down to the difference between transactions and calls.  The thing about calls is that they only return a value, not a status.  So, they actually do not contain sufficient information to determine whether they reverted.

Now, *if* the call reverted with a message, then (notionally speaking) web3 could check for the presence of an encoded revert message (these are pretty distinctive) and throw an exception if present, though it doesn't actually do this.  And notionally speaking *we* could do this if we used web3 slightly differently, although I'm unsure if it's worth it for us to do this, or even correct for us to do this, when we're planning to rewrite Truffle Contract anyway.  But neither Truffle nor web3 could possibly detect a reverting call *in general*, because the information simply isn't there.  (Maybe there's no reason.  Or maybe they did some crazy assembly to provide a revert message outside of the standard format.  Etc.)

So why do reverting calls still cause exceptions in certain cases, given that I just said that they don't?  Well, if you use Ganache, and you don't turn on the `--noVMErrorsOnRPCResponse` option to force it to operate in a strictly standard way, then Ganache itself will return an error when a call reverts, rather than the result as expected, and so web3 will throw an exception.  But if your client is acting in a standard fashion, then, as mentioned, web3 won't do this.

I think recent or upcoming versions of Geth may be adding some sort of thing like this, but I'm not too clear on the details, and I don't know whether it will be in a format that causes web3 to throw an exception.  Sorry, haven't kept up on this.

In any case, like I said, if you want a quick workaround, do it as a transaction rather than a call.  We possibly could do something about this on our end, but I'm not certain that we should.  If you reopen the issue then I guess we'll have to discuss it, but for now I'm leaving this alone.  Hope that's helpful!

**Comment by Jaime-Iglesias** [comment]
> I can explain what's going on here. I won't reopen this unless you think it should be reopened, but I can certainly explain what's going on here.
> 
> So, before I go on, I should say, there is a quick workaround for your problem. Your problem is occurring because `foo` is a `pure` function, and therefore, by default, when you do `calculator.foo(a, b)`, Truffle defaults to performing a call rather than a transaction. However, you can do `calculator.foo.sendTransaction(a, b)` in order to force it to make an actual transaction. If you do this, you should get the exception you expect.
> 
> Now then: Why is this happening?
> 
> First, I should note that this doesn't really have to do with revert _reasons_. Rather it has to do with, do reverts cause exceptions? In web3, reverts cause exceptions, and Truffle (which uses web3) preserves this behavior. But when we say "reverts cause exceptions", this really means "reverting _transactions_ cause exceptions". Reverting calls do not cause exceptions in web3... usually. I'll talk about an exception to this in a bit.
> 
> So why don't reverting calls cause exceptions in web3? Well, it comes down to the difference between transactions and calls. The thing about calls is that they only return a value, not a status. So, they actually do not contain sufficient information to determine whether they reverted.
> 
> Now, _if_ the call reverted with a message, then (notionally speaking) web3 could check for the presence of an encoded revert message (these are pretty distinctive) and throw an exception if present, though it doesn't actually do this. And notionally speaking _we_ could do this if we used web3 slightly differently, although I'm unsure if it's worth it for us to do this, or even correct for us to do this, when we're planning to rewrite Truffle Contract anyway. But neither Truffle nor web3 could possibly detect a reverting call _in general_, because the information simply isn't there. (Maybe there's no reason. Or maybe they did some crazy assembly to provide a revert message outside of the standard format. Etc.)
> 
> So why do reverting calls still cause exceptions in certain cases, given that I just said that they don't? Well, if you use Ganache, and you don't turn on the `--noVMErrorsOnRPCResponse` option to force it to operate in a strictly standard way, then Ganache itself will return an error when a call reverts, rather than the result as expected, and so web3 will throw an exception. But if your client is acting in a standard fashion, then, as mentioned, web3 won't do this.
> 
> I think recent or upcoming versions of Geth may be adding some sort of thing like this, but I'm not too clear on the details, and I don't know whether it will be in a format that causes web3 to throw an exception. Sorry, haven't kept up on this.
> 
> In any case, like I said, if you want a quick workaround, do it as a transaction rather than a call. We possibly could do something about this on our end, but I'm not certain that we should. If you reopen the issue then I guess we'll have to discuss it, but for now I'm leaving this alone. Hope that's helpful!

@haltman-at  That was actually VERY helpful - I never thought of thinking about it as in `send` vs `call`, I guess that the fact that I was getting and actual value returned with the Solidity encoding for a revert should have given that away.

One of the biggest sources of confusion in the whole thing was able to get some revert messages  from my local node (actually all but this particular test against a `pure` function) and all of them against Ganache (where everything works just fine) and that was making pointing-out where the "error" was very hard.

Now with this explanation and the added knowledge of `--noVMErrorsOnRPCResponse` this makes much more sense and I will certainly try to specifically transform the `call` into a `send` for this particular test.

That was ver helpful - I really appreciate the thorough explanation.

As a side question, I've been getting a random error that comes and goes when testing against my local node, specifically:

```
     Error: Number can only safely store up to 53 bits
     at PromiEvent (node_modules/@truffle/contract/lib/promievent.js:9:30)
```

The error comes and goes (in different parts of my testes), so it's very hard for me to really tell what's going on.

Again, thank you for the explanation - I don't think there's a need for re-openning the issue. perhaps it could be helpful to mention this somewhere in the documentation for future reference (if that's not already the case) ?

**Comment by Jaime-Iglesias** [comment]
Actally, I solde the `53 bits` problem the same way too , so thx again.

**Comment by haltman-at** [comment]
Oh, OK!
