### ISSUE TITLE
Installing @truffle/contract fails if git is not installed

### ISSUE THREAD

**Issue by whittlem** [trufflesuite/truffle#3390]
- [ N ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

@truffle/contract does not install on a fresh install of Ubuntu 20.04

# npm i @truffle/contract
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-24T06_08_27_393Z-debug.log

Error log has this...

1030 verbose stack Error: spawn git ENOENT
1030 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
1030 verbose stack     at onErrorNT (internal/child_process.js:415:16)
1030 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
1031 verbose cwd /root/truffleproject
1032 verbose Linux 5.4.0-48-generic
1033 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "@truffle/contract"
1034 verbose node v10.19.0
1035 verbose npm  v6.14.4
1036 error code ENOENT
1037 error syscall spawn git
1038 error path git
1039 error errno ENOENT
1040 error enoent Error while executing:
1040 error enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
1040 error enoent
1040 error enoent
1040 error enoent spawn git ENOENT
1041 error enoent This is related to npm not being able to find a file.
1042 verbose exit [ 1, true ]

## Steps to Reproduce

# npm --version
6.14.4

~/truffleproject# npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (truffleproject) 
version: (1.0.0) 
description: 
entry point: (truffle-config.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /root/truffleproject/package.json:

{
  "name": "truffleproject",
  "version": "1.0.0",
  "description": "",
  "main": "truffle-config.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

# npm i @truffle/contract
*** INSTALLING ***

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

## Expected Behavior

It to install with no issue

## Actual Results

# npm i @truffle/contract
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-24T06_12_26_450Z-debug.log

## Environment

* Operating System: Ubuntu 20.04 running on VirtualBox
* Ethereum client: geth 1.9.21-stable / solc 0.7.1+commit.f4a555be.Linux.g++
* Truffle version (`truffle version`): v5.1.45
* node version (`node --version`): v10.19.0
* npm version (`npm --version`): 6.14.4

**Comment by gnidan** [comment]
Hm, any reason why you need that specific version?

I just tried latest and 4.0.33 and both install (but I'm on a Mac). Could you try installing latest and see if that works for you?

**Comment by whittlem** [comment]
Apologies, I started with the latest version but when that didn’t work I tried earlier versions. I get exactly the same error message without specifying a version.

If this worked for you on Ubuntu 20.04 can you let me know which  relevant versions you are running?

**Comment by whittlem** [comment]
Apologies, I had started with the latest version but when that didn't work I started trying other versions and copied the wrong output. I've updated the Issue above with what I started with.

**Comment by gnidan** [comment]
Oh darn. Thought we got rid of this problem. Looks like @truffle/contract needs git installed. We'll look into fixing this, but in the meantime, it should work if you install git first.

**Comment by whittlem** [comment]
Many thanks, just to confirm installing 'git' first fixed this. You could close this for me but would be good if you could fix this automatically for others.

**Comment by eggplantzzz** [comment]
@whittlem Thanks for confirming. We are going to try and fix this, we'll leave this issue open for now to track the problem.

**Comment by fainashalts** [comment]
We're not sure what's causing this but will look into it, thanks @whittlem!

**Comment by mrokams** [comment]
You need admin permissions to install NPM packages globally, use the command : **sudo npm install -g truffle**

**Comment by moyu597** [comment]
tried "npm install truffle"
and also have git installed but get the error
`
Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated cids@1.1.9: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@3.2.1: This module has been superseded by the multiformats module
npm WARN deprecated ipld-dag-pb@0.20.0: This module has been superseded by @ipld/dag-pb and multiformats
npm WARN deprecated ipld-raw@6.0.0: This module has been superseded by the multiformats module
npm WARN deprecated ipld-dag-cbor@0.17.1: This module has been superseded by @ipld/dag-cbor and multiformats
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module
npm WARN deprecated @nodefactory/filsnap-adapter@0.2.2: Package is deprecated in favour of @chainsafe/filsnap-adapter
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN notsup Unsupported engine for graphql-executor@0.0.18: wanted: {"node":"^12.22.0 || ^14.16.0 || >=16.0.0"} (current: {"node":"14.15.4","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: graphql-executor@0.0.18

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/og/.npm/_logs/2022-03-12T13_28_13_592Z-debug.log`

**Comment by cds-amal** [comment]
Hello @moyu597, your errors are not related to `git` installation status. According to the errors, the `npm` command failed because of permission errors. Usually, this is because `sudo` was previously used to elevate privileges when installing node, or running `npm`. 

You'll have to fix your environment before proceeding. Start with running `npm doctor` and followup on its output. Good luck!

**Comment by haltman-at** [comment]
Closing this for issue maintenance.
