### ISSUE TITLE
truffle suite installation

### ISSUE THREAD

**Issue by CEDABASE** [trufflesuite/truffle#3423]
Hello everyone, I would like to ask you for help about installing T Volant. I can't install it by typing the installation code "npm install -g truffle" in the control of my windows 10 computer. could you direct me in a simple way for installation please? because the documentation about is not clear enough and I try all the recommendations described in the site ''trufflessuite'' but nothing works. While waiting for your response, I wish you a great day and thank you in advance.

**Comment by eggplantzzz** [comment]
Hey @CEDABASE, do you have npm installed? You will need to install npm in order to install Truffle. You can find some docs for that [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm). If you already have it installed then can you provide some more details about the problem you are experiencing? Thanks!

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance.
