### ISSUE TITLE
Compile-solidity should store metadata at compilation level

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#3533]
The `compile-solidity` package currently deals with metadata on a per-contract basis, but since the metadata is the same  for the whole compilation we should store it on a per-compilation basis.

**Comment by haltman-at** [comment]
I don't think the premise of this issue is correct.  *Most* of the metadata only depends on the compilation, but parts -- specifically, the `output` parts -- depend on the particular contract.  As such, I don't think it makes sense to treat metadata as a compilation-level thing, unless perhaps one wants to perform processing to split it into compilation-level and contract-level parts, which I don't think we want to do (we typically want to treat it as opaque).  (@gnidan?)

**Comment by gnidan** [comment]
Will metadata ever differ for two contracts in the same compilation?

**Comment by haltman-at** [comment]
Yes, the `output` parts of the metadata contain contract-specific information, as I mentioned above.  For instance, they include the contract's ABI.

**Comment by gnidan** [comment]
Oh, cool. Good to know. Thanks!
