### ISSUE TITLE
Migrations contract should be Ownable so that it includes transferOwnership — helpful with Gnosis Safe workflow

### ISSUE THREAD

**Issue by marsrobertson** [trufflesuite/truffle#3570]
### Current `Migrations.sol`

https://github.com/trufflesuite/truffle/blob/1f9ab16819b7e0ea994a9add63d35d6a74932985/packages/core/lib/commands/init/initSource/contracts/Migrations.sol#L4-L19

Currently **ONLY OWNER** can call the function.

I suggest adding `transferOwnership` function so that the ownership can be passed to the Gnosis Safe Multisig.

Suggested upgrade process:
- `transferOwnership` to a EOA (externally owned account)
- use that EOA to `prepareUpgrade`
- use Gnosis Safe Multisig and OpenZeppelin app to actually trigger the upgrade
- `transferOwnership` from EOA back to Gnosis Safe Multisig

Adding the `transferOwnership` is trivial: making `Migrations` `Ownable`

Source: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol 

**MAIN QUESTION:** are there any unintended consequences, negative side effects, problematic issues?

### Related

Massively inspired by this tutorial: https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-truffle/3579

```
// migrations/4_prepare_upgrade_boxv2.js
const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');
 
const { prepareUpgrade } = require('@openzeppelin/truffle-upgrades');
 
module.exports = async function (deployer) {
  const box = await Box.deployed();
  await prepareUpgrade(box.address, BoxV2, { deployer });
};
```

In my workflow, the ProxyAdmin and the guy who has all the permissions is Gnosis Safe. The deployer is EOA (regular account). I'm thinking about `transferOwnership` to Gnosis Safe. But it is not transferable... I think that adding `TransferOwnership` it is a simple acceptable change?

**Comment by eggplantzzz** [comment]
Hey @marsrobertson, thanks for the suggestion. Actually we are kind of moving in the direction of making the Migrations contract not part of the default Truffle workflow. In the future, we will continue to support this contract but it doesn't seem to really make sense for us to make it more robust. 

However, currently you are totally able to make whatever edits you want to this contract and it should be fine after migrations are complete. During migrations Truffle does need access to this contract because it interacts with this contract from an EOA. Is this ok or did you want to propose something different?

**Comment by fainashalts** [comment]
Hi @marsrobertson we are closing this issue for maintenance, but if you need any help relating to this issue, feel free to open a new issue!
