### ISSUE TITLE
Truffle not finding contract 

### ISSUE THREAD

**Issue by najienka** [trufflesuite/truffle#370]
Hi

Please, I get the following error when i compile but the contract is in the contract directory.
I am using truffle version 2.1.0
I urgently need to solve this issue. Any help is appreciated 

Compiling bankGuarantee.sol...
Error compiling:

Could not find expected contract or library in 'bankGuarantee.sol': contract or library 'bankGuarantee' not found.
Compiliation failed. See above.

**Comment by tcoulter** [comment]
This is a restriction in Truffle 2.1 and 3.1.x where your filename must match the contract name exactly. Since your file name is `bankGuarantee.sol`, Truffle expects you to have the following code in that file:

```
// Name must match exactly! lowercase b!
contract bankGuarantee {
  // ...
}
```

Truffle 3.2 will remove this restriction. If you want to upgrade to Truffle 3.0 from Truffle 2.0 to get rid of this restriction, see this upgrade guide: http://truffleframework.com/tutorials/upgrading-from-truffle-2-to-3
