### ISSUE TITLE
Vyper compile fails with "SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by acryptosx** [trufflesuite/truffle#3755]
Truffle 5.1.57 is last version where vyper compiles, 5.1.58 to 5.1.64 fails with:

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-vyper/index.js:151:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-vyper/index.js:79:1
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)

**Comment by gnidan** [comment]
Uh oh! What version of Vyper? Any other project info you can share?

(@haltman-at, you'll want to see this!)

**Comment by acryptosx** [comment]
vyper --version
0.2.7+commit.0b3f3b3

**Comment by haltman-at** [comment]
Hm, I'm not encountering any problems when I try it... do you have a reproduction example I could check out?  Thank you!

(Actually it's quite curious that it's erroring at at `JSON.parse` in `index.js`, since that would mean that it's attempting to compile with `vyper` rather than `vyper-json`, even though you're using Vyper 0.2.7.  I guess you somehow only installed `vyper` and not `vyper-json`?  Interesting.  Well, it ought to work with or without `vyper-json`, so this is still a bug either way.)

Anyway like I said, I think I'm going to need a reproduction example here to find out just what's going wrong.  Would you be able to provide one?

**Comment by haltman-at** [comment]
Oh, silly me -- I forgot to disable my own `vyper-json` before attempting to reproduce this.  I've reproduced it just fine now.  OK, I'll have to see what's causing this.  Thanks for the report!

**Comment by haltman-at** [comment]
OK, I've put up #3757 to fix this!

**Comment by acryptosx** [comment]
Is it better to install vyper-json? The docs are a bit sparse on using vyper with truffle.

**Comment by haltman-at** [comment]
Well, once we merge the PR above and do the release this week, ordinary `vyper` should work fine again.  But yeah, our documentation on using Vyper with Truffle is pretty sparse, no question.  To a large extent that's because until recently our support for using Vyper with Truffle was itself pretty bare!  We've been working on improving it lately but didn't really updated the documentation accordingly.  I guess we'll have to do that.  But yes, much of the various new stuff we've recently added with Vyper -- import analysis to avoid recompiling everything, versatile imports like we support with Solidity -- will only work with `vyper-json`.

In this case, I didn't notice the problem until you reported because for this particular problem to occur, you had to not only be using `vyper` rather than `vyper-json`, but also using a non-prerelease version of Vyper.  I forgot to test that case, because when installing Vyper via pip, it will install both if you specify a version that has them both, and so I only tested `vyper` proper with versions from before `vyper-json` existed.

So, uh, thanks for alerting us that this is a case to look out for.  Likely we should start making use of `vyper --standard-json` when that's available, to make things easier and more robust.  But for now yes things will work better with `vyper-json`.  And I suppose that will always be the case on older versions of Vyper that have `vyper-json` but not `vyper --standard-json`.

**Comment by acryptosx** [comment]
Wow, I am impressed by the quick and detailed response, thank you so much 🙃

**Comment by haltman-at** [comment]
Of course! And I've now also put up #3759, so after this week's release you should no longer need `vyper-json` installed to get the benefits of such (assuming you're using Vyper 0.2.5 or later, which you are). :)

**Comment by haltman-at** [comment]
OK, these fixes are released now!
