### ISSUE TITLE
Out of memory, Migrate

### ISSUE THREAD

**Issue by francovilla** [trufflesuite/truffle#3778]
FATAL ERROR: NewNativeModule Allocation failed - process out of memory

When I go to Migrate, that happens to me, how can it be solved?(My laptop at that exact moment has 7GB free of RAM left)

I also noticed that Node occupies only 500mb of those 7GB which remains 6GB totally free

Thanks🙏

**Comment by gnidan** [comment]
Hey @francovilla could you try upgrading to the latest Truffle v5.1.67? We just made some rather significant performance improvements to the Truffle bundle, and I'm hopeful that this sort of memory problem will now not be a problem.

If that isn't the case, you can always try giving Node.js more memory, e.g. (instead of `truffle migrate`):
```console
$ node `which truffle` --max-old-space-size=8192 migrate
```

Please let us know! Sorry about this.

**Comment by davidmurdoch** [comment]
Closing for issue maintenance.
