### ISSUE TITLE
Debugger: msg.value not updating 

### ISSUE THREAD

**Issue by zach-is-my-name** [trufflesuite/truffle#3864]
Below you'll see that ```web3CallWithTruffleContract()``` produces transaction ```txHash```

When I running Truffle debugger on ```txHash``` The msg property value === 1 **before each** require, despite that msg.value changing after the first external sub-call.  Initially, I didn't know why the transaction was failing because the debugger reverted before entering the second ```sendValue``` call, and I thought msg.value was fixed for the duration of the transaction (although now I know it isn't, and it's clear why).  Despite all this msg.value display doesn't (or at least didn't) change to reflect the actual msg.value for that message call.

```
contract KnownContract {
  function sendValue(uint gaslimit, uint gasprice) external payable {
     require(msg.value == gaslimit *gasprice, "msg.value must == gaslimit * gasprice);
     address someAddress = 0x55... ;
     someAddress.transfer(gaslimit * gasprice);     
  }
}

contract Contract {

KnownContract knownContract

  function() payable external {}
  function callKnownContract(uint gaslimit, uint gasprice) public payable {  
    knownContract = KnownContract(0x10...);
    knownContract.sendValue(gaslimit * gasprice)(gaslimit, gasprice);
    knownContract.sendValue(gaslimit * gasprice)(gaslimit, gasprice);

  }
  

}


function web3CallWithTruffleContract(gaslimit, gasprice) {
   Contract.callKnownContract(gaslimit, gasprice, {value: 100})
}  

   web3CallWithTruffleContract(10, 10)

```

* Operating System: ubuntu 20.04
Truffle v5.1.66 (core: 5.1.66)
Solidity - 0.5.1 (solc-js)
Node v12.6.0
Web3.js v1.2.9

**Comment by haltman-at** [comment]
Oh, huh.  But, I'm a bit confused as to what exactly the issue is here.  You say that `msg.value` is showing the wrong value -- where is it showing the wrong value?  In the `sendValue` call?  What is it showing instead?  I'm a little confused here.

I'll try to reproduce this, but I'd like to have a clearer explanation of just what the error is here.

(Also, I'm assuming that
`knownContract.sendValue(gaslimit * gasprice)(gaslimit, gasprice)` is supposed to be `knownContract.sendValue.value(gaslimit * gasprice)(gaslimit, gasprice)`?  Your code is also a bit confusing because you seem to have Solidity and JS mixed together, it took me a moment to piece that together...))

**Comment by haltman-at** [comment]
OK, on trying this out myself, I'm not seeing any problem here.  `msg.value` remains at 100 throughout, as it should.  From your original issue report, you seem to be implying that `msg.value` should decrease after sending ether?  That's incorrect; `msg.value` refers to the amount of wei sent to the current call; it remains constant throughout each EVM stackframe.  It can change during a transaction if you make an external call, as you do here, but it will return to its previous value once that external call exits.  In this case, all your external calls are sent with 100 wei, so `msg.value` remains at 100 throughout, and the debugger correctly reflects this.

I think the confusion here is coming from the fact that the transaction reverts.  The transaction isn't reverting here because of the second `require`; it's reverting because you don't have enough ether to make the second call.  Note that the revert happens before it ever reaches that second require.  Indeed, you note this yourself.

So, as best I can tell, there's no issue here.  Am I mistaken?  Apologies, I've had to rely a bit on inference as your issue is a bit unclear, but I'm pretty sure all that's going on here is that `msg.value` doesn't work how you thought it worked.  Let me know if I'm wrong and there is an actual problem here.

Note that Solidity globally-available variables basically all just correspond to some EVM opcode; in this case, it's the `CALLVALUE` opcode.  The EVM doesn't provide the functionality to track the current call value minus any ether sent, nor does Solidity provide that functionality on top of it.

**Comment by zach-is-my-name** [comment]
Okay, first off if I'm wrong, I'm sorry.  But there seemed to strong alignment between the behavior I was seeing and this from Solidity docs: 

> "The values of all members of msg, including msg.sender and msg.value can change for every external function call. This includes calls to library functions."

_So I'm making two external function calls, "member" is changing, no? That's what I gathered from my similar test case.  I had the identical require, and reverted on the second require when I sent {value: 1} despite the debugger showing msg.value as == 1 just prior to that require._  

I apologize if not responding to your reply fully, I couldn't cringe at _myself_ long enough to do that

**Comment by zach-is-my-name** [comment]
Yes, that's all clear, thank you.  I didn't really expect there to be an issue with the debugger's msg.value, but on the other hand I was profoundly confused why for instance, sending _enough_ ether would make it appear that the displayed msg.value directly contradict the require's. And conversely matching msg.value from the debugger to require condition would cause it revert
