### ISSUE TITLE
"Error: Could not find artifacts for" when deploying contracts from node_modules

### ISSUE THREAD

**Issue by haydenyoung** [trufflesuite/truffle#3951]
When compiling and deploying a contract from a node modules source, I'm seeing the following:
```
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for /@uniswap/v2-core/UniswapV2Pair from any sources
```
which seems to be exactly related to https://github.com/trufflesuite/truffle/issues/1791.

I'm running v5.2.3.

Could it have been reintroduced?

Thanks

**Comment by eggplantzzz** [comment]
Thanks for opening this, could you provide us with some code and steps to recreate this error?

**Comment by haydenyoung** [comment]
thanks for the response.

To replicate:

Set up a simple project:

```
mkdir TestProject
cd TestProject
truffle init
npm init
```
Install the uniswap core:

```
npm i --save @uniswap/v2-core
```
Create a migration script, something like 2_testproject.js.

In 2_testproject.js, add:

```
const UniswapV2Pair = artifacts.require("@uniswap/v2-core/UniswapV2Pair");

module.exports = function (deployer) {

};
```
With a local blockchain running (e.g. ganache) and the development config uncommented in truffle-config.js, run:

```
truffle migrate
```

This should result in:

```
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
```

It may be I have the require referenced incorrectly.

Let me know if you need any more information.

**Comment by eggplantzzz** [comment]
I see what the problem is, right now Truffle expects npm packages to be Truffle projects while that uniswap library has a different structure. Truffle can't seem to locate the artifact because of this difference in structure. As a workaround for now you could just copy the artifact file (the JSON file from `./node_modules/build` manually into your project's `build/contracts` directory and Truffle should find it.

Perhaps we should consider making Truffle look in the `build` directory for npm packages? Seems like it could be a common place that artifacts are kept.

**Comment by eggplantzzz** [comment]
I put in [this PR](https://github.com/trufflesuite/truffle/pull/3973) to check the `build` folder of packages installed by npm.

**Comment by haydenyoung** [comment]
Thanks @eggplantzzz looks great. Yeah at the moment I am using the "copy over to my build/contracts" fix as you stated and that is working for me.

Thanks again.
