### ISSUE TITLE
someMethod(arg1, arg2) & someMethod.call(arg1, arg2) don't work the same

### ISSUE THREAD

**Issue by valexandersaulys** [trufflesuite/truffle#4074]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

While writing a contract, if I write a test using `token.someMethod(arg1, arg2)`, it will execute. 

However, if I write a test with `token.someMethod.call(arg1, arg2)` it will _not execute_. 

Is this explicitly documented anywhere? its incredibly important.

## Steps to Reproduce

Create an ERC20 token, use an implementation (I used OpenZeppelin), and fire up the following

```javascript
truffle(development)> let thing = await ERC20Token.deploy();
 truffle(development)> thing.approve(accounts[1], 20);
// truncated trasnaction output
 truffle(development)> thing.allowance(accounts[0], accounts[1]);
BN { negative: 0, words: [ 20, <1 empty item> ], length: 1, red: null }
 truffle(development)> thing.allowance.call(accounts[0], accounts[1]);
BN { negative: 0, words: [ 20, <1 empty item> ], length: 1, red: null }
 truffle(development)> thing.approve.call(accounts[1], 15);
true
 truffle(development)> thing.allowance.call(accounts[0], accounts[1]);  // THIS IS INCORRECT
BN { negative: 0, words: [ 20, <1 empty item> ], length: 1, red: null }
 truffle(development)> thing.approve.call(accounts[1], 15);
true
 truffle(development)> thing.allowance.call(accounts[0], accounts[1]);
BN { negative: 0, words: [ 20, <1 empty item> ], length: 1, red: null }
 truffle(development)> thing.approve(accounts[1], 15);
// truncated transaction output
 truffle(development)> thing.allowance(accounts[0], accounts[1]);
BN { negative: 0, words: [ 15, <1 empty item> ], length: 1, red: null }
 truffle(development)> .exit
```

## Expected Behavior

I expected `.someMethod.call(args)` and `.someMethod(args)` to execute the same way.

## Actual Results

Both functions did not execute the same way -- one didn't execute at all

## Environment

* Operating System: Ubuntu 20.04.2 LTS x86_64
* Ethereum client: Not sure? Solc is 0.8.0
* Truffle version (`truffle version`): Truffle v5.3.7 (core: 5.3.7)
* node version (`node --version`):  v15.14.0
* npm version (`npm --version`):  7.7.6

**Comment by valexandersaulys** [comment]
Giving this a think over, is the issue that `.sometMethod.call()` does not execute a transaction but `.sometMethod()` does?

Is that why a transaction block is returned during testing?

**Comment by haltman-at** [comment]
Yes, exactly.  The `.call` method is for performing a call rather than a transaction.  More specifically:

* `method.sendTransaction()` will always perform a transaction (and get the transaction's receipt, among other things)
* `method.call`() will always perform a call (as in, do not perform a transaction, but do get the method's return value)
* `method()` will perform a call for methods that are `view` or `pure`, and a transaction otherwise.

This actually is documented [here](https://www.trufflesuite.com/docs/truffle/getting-started/interacting-with-your-contracts#special-methods-on-truffle-contract-objects), and in a few other places, although I'll admit it's probably not findable enough, and we should probably improve that.

Hope that's helpful!

**Comment by valexandersaulys** [comment]
Yes ok, makes sense. 

`sendTransaction` makes me think "send money to contract" which is _quite_ the meaning here. Rather, it means to execute that method and send that executed transaction to the blockchain. 

Many thanks for the quick reply!
