### ISSUE TITLE
"Truffle Init" has no package.json?

### ISSUE THREAD

**Issue by JimLynchCodes** [trufflesuite/truffle#4105]
When I run `npm init` it scaffolds all the solifity and js files but no package.json...

this is very bizarre to me... packages that may need to be installed need a package.json file.

why is there no package.json scaffolded with the project?

another advantage of this is that you can prefill some common npm commands...

```
"scripts": {
    "start": "truffle develop",
    "test": "truffle test"
  },
```

**Comment by gnidan** [comment]
The reason for this is because (perhaps historically) Truffle doesn't want to tie itself to NPM directly, so `truffle init` takes the approach to omit this file.

Also: what would we populate it with? Upon running `truffle init`, Truffle has no idea what you want your package name to be, the license, etc., so this (still) doesn't strike me as something we want as a feature enhancement... maybe we could add some messaging after `truffle init` to suggest "hey, maybe you want to `npm init` also!"?

Since you're only asking the question here, would you mind closing this issue if your question is answered sufficiently, or reword this issue so that it represents something actionable? Maybe that just means adding messaging, or if you have clear requirements in mind for the contents of `package.json`, you could structure this as an enhancement request, and we can continue the discussion accordingly.

Thanks for bringing it up!

**Comment by JimLynchCodes** [comment]
Thanks @gnidan!

I don't see why you don't want to be tied to npm...

Since it is installed via npm, it pretty much is. Having this is in the dev dependencies of the project would also make it easier for developers to more easily use a consistent version of truffle.

The default license that npm uses is ISC so I think that would be fine.

I think this would be a decent one to include in truffle init:

```json
{
  "name": "<new truffle project>",
  "version": "0.0.1",
  "description": "",
  "main": "",
  "scripts": {
    "start": "truffle develop",
    "test": "truffle test"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "truffle": "^5.3.10"
  }
}
```

If for some reason the user doesn't want to the package.json then he or she can delete it. 😉

But once you get deep into developing with truffle you end up wanting to use truffle-assert, nodemon, etc. and realize that you really need a package.json at the very least for keeping track of your dependencies.

**Comment by kevinbluer** [comment]
Hey @JimLynchCodes, we've been discussing this internally and are leaning towards being less opinionated and allowing devs to setup their own tooling. In addition, truffle doesn't need to install the `package.json` because `npm install <package> --save` will generate it.

Team consensus is still leaning towards adding messaging to the end of the `truffle init` output to suggest useful next commands.

Lastly, just for reference you can also use `truffle unbox <username>/<repo>` if you want to [create a box](https://www.trufflesuite.com/docs/truffle/advanced/creating-a-truffle-box) for your own preferred configuration.

Thanks so much for all your thoughts / input on this! Also leaving it open so we can continue to have discussion on this as needed.
