### ISSUE TITLE
truflle init is not working ??? i have a solution for you guys :)

### ISSUE THREAD

**Issue by harshmamgai** [trufflesuite/truffle#4172]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

truflle init is not working ??? i have a solution for you guys :)

simply open your command line and write  **truffle init --force** instead of truffle init

**Comment by haltman-at** [comment]
Hi, this is the issue tracker, for reporting issues with Truffle.  You don't appear to have an actual issue here, but rather usage advice?

I'm going to go ahead and close this, if you don't mind, but if you think `truffle init --force` is insufficiently documented, you could open an issue for that.  Thanks!
