### ISSUE TITLE
Could not connect to your Ethereum client

### ISSUE THREAD

**Issue by aster2709** [trufflesuite/truffle#4233]
- [✅ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
On running ```truffle test``` or ```truffle migrate```

```Something went wrong while attempting to connect to the network```
```Could not connect to your Ethereum client```
![image](https://user-images.githubusercontent.com/39130640/128458816-59853277-acb8-4b63-b5fa-7ef2f2c58ff8.png)

**here is my truffle config**
![image](https://user-images.githubusercontent.com/39130640/128458952-3f455134-1d42-43fa-816c-355bb20646b3.png)

## Steps to Reproduce
Minimal Reproduction: 
```truffle unbox metacoin```
_uncomment development and test networks_

now try running ```truffle test``` or ```truffle migrate```

## Environment

* Operating System: Ubuntu 20.04 
* Truffle version (`truffle version`): 5.4.3
* node version (`node --version`): 14.17.1
* npm version (`npm --version`): 7.18.1

**Comment by eggplantzzz** [comment]
Hey @aster2709, the problem here is that you have a `development` and `test` network defined in your `truffle-config.js`. If you have a configuration there with either of those names, it will assume you want to connect to a network at one of those configurations (I think it will default to `development` over `test`) and attempt to connect. Since you haven't started a network there it will give you the message you are reporting here and error. If Truffle doesn't find a configuration with one of those two names it will spin up its own instance of Ganache under the hood. So this is actually intended behavior.

**Comment by aster2709** [comment]
I see, so I've kept just development, it still throws with the same error. as you said, it should have spun up ganache internally right?
![image](https://user-images.githubusercontent.com/39130640/128523956-9b6e5c9c-4ba6-47a3-91f6-1dbe5b095aad.png)

**Comment by fainashalts** [comment]
@aster2709 you do have to run ganache in a separate tab (`ganache-cli`, or specify the port with `ganache-cli -p 7545`). Have you done that? If you want a ganache instance spun up for you, then try running `truffle develop` to spin up a REPL, and in there you can run all of your commands without the `truffle` prefix -- so just `test`, `migrate`, `compile`, etc. 

I hope that helps!

**Comment by aster2709** [comment]
@fainashalts understood, thank you!
