### ISSUE TITLE
"methods" is always empty...

### ISSUE THREAD

**Issue by JimLynchCodes** [trufflesuite/truffle#4380]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

the created json ABI files has a "methods" field that is always an empty object...

## Steps to Reproduce

just confirmed this happens with every new project:
truffle init
truffle create all Hello
add a function to Hello contract:
function foooo() external pure returns (string memory) {
    return "something";
  }
4.  run truffle build
5. Look at build/contracts/Hello.json and see that "methods" is just an empty object... 

## Expected Behavior

Methods should appear in "methods" field

## Actual Results

THEY DON'T

## Environment

Truffle v5.4.10 (core: 5.4.10)
Solidity v0.5.16 (solc-js)
Node v14.17.3
Web3.js v1.5.2
 npm: '6.14.13'

**Comment by haltman-at** [comment]
Could you explain what information you expect to appear in `methods`, other than that it would be something about the methods?  Truffle artifacts do not in fact have a `methods` field, so it's not a bug that it's missing.  As such, I'm not clear on why you expect there to be a `methods` field, what you expect it to contain, or what you intend to use this information for.

Now, you say that `methods` appears as an empty object; but given that there is no `methods` field in the first place, I suspect that you are actually looking at the `methods` *subfield* of either the `devdoc` field or the `userdoc` field.  These fields will only be populated if you use [NatSpec comments](https://docs.soliditylang.org/en/v0.8.9/natspec-format.html) for documentation; if you do that, they will then contain that documentation.  Since your contract does not use NatSpec comments, it is not an error that these subfields are empty.

You might also be thinking of the `methods` property that exists on Truffle contract abstractions.  If *this* is empty, then that is certainly a bug!  However, a Truffle contract abstraction, a Javascript object, is a different thing from a Truffle artifact, a JSON file, even if the contract abstraction contains many of the fields of, and is created from, an artifact.  You will not see a contract abstraction's `method` object in the artifact JSON.  That `methods` object, of course, is created from the artifact's `abi` field, which does list the contract's methods, among other things.

So, as mentioned, it's not clear to me what you were expecting to find here.  Does the above explanation resolve your issue, or is there work still to be done here?

**Comment by JimLynchCodes** [comment]
thanks @haltman-at, but I have no clue what you are talking about...

My issue was that I needed to import the Abi json **_AND_** read the ".abi" field off of it. 👍

**Comment by haltman-at** [comment]
OK!  I should point out, though, that the JSON files you are looking at is *not* the ABI JSON.  It's the Truffle Artifact.  It *contains* the ABI JSON, in the `abi` field, which is what you extracted.
