### ISSUE TITLE
Dependency contracts are not available in tests unless a truffle project's contract use them.

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle#450]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Dependency contracts are not available in tests unless a truffle project's contract use them.

## Steps to Reproduce

Create a new truffle project with a npm dependency (example: `npm i zeppelin-solidity`). Create a test that uses one of the dependency contracts that's not required by any of the main project's contracts. Truffle will say it can't find the file, because it will look into the build folder and it won't find it there.

## Expected Behavior

Truffle tests should be able to use any dependency contract, not only those used by the project's contracts.

## Actual Results

Can't find the contract and test fails.

## Environment

* Operating System: Distributor ID:	Ubuntu 16.10
* Truffle version:Truffle v3.2.5
* Ethereum client: testrpc
* node version: v8.0.0
* npm version: 5.0.3

**Comment by interfect** [comment]
I can reproduce this (at least in migrations) on Truffle 4.1.3.

I have a project with a dependency on the `macroverse` NPM module. In a migrations script I try to do:

```
var RealMath = artifacts.require("macroverse/contracts/RealMath.sol");
```

This does not work.

I can add a `Workaround.sol` to my project's `contracts` folder consisting of:

```
import "macroverse/contracts/RealMath.sol";
```

If I do that and a `truffle compile`, the dependency's contract is built into `build/contracts/RealMath.json` and is available to the migration script.

I *need* to be able to use the JSON files in `node_modules/macroverse/build/contracts/*.json` from my dependent project, however, as those files from the dependency contain the mainnet addresses of the deployed contracts which the dependent project's migration scripts are going to need to have available. I am pretty sure this workaround results in new artifacts being built in `build/contracts/*.json` with empty `networks` fields.

I *used* to be able to get at the dependency's artifacts as just `artifacts.require("macroverse/RealMath.sol")`, in about Truffle 3.0. Since updating to 4.1.3 that hasn't worked and I haven't been able to find anything else that does. `macroverse/build/contracts/RealMath.json` and `macroverse/build/contracts/RealMath` don't work, for example. Also, there's the syntax shown in [the documentation](http://truffleframework.com/docs/getting_started/packages-npm) for use in migration scripts:
```
// Note that artifacts.require takes care of creating an abstraction for us.
var SimpleNameRegistry = artifacts.require("example-truffle-library/SimpleNameRegistry");
```

That would be `macroverse/RealMath` for me, which also doesn't work.

The other approach suggested in the documentation is something like:

```
var contract = require("truffle-contract");
var RealMath = contract(require("macroverse/build/contracts/RealMath.json"));
```

This lets me create *something*, but it's not the same type as what you get from artifacts.require, and in particular I'm not sure how to link or deploy it.

**Comment by ConnorChristie** [comment]
I figured out a workaround without having to do anything extra fancy! The reason this isn't working as intended is due to this pesky [resolverintercept](https://github.com/trufflesuite/truffle/blob/master/packages/truffle-migrate/resolverintercept.js) which aims to bring caching to the contract lookup functionality. ...however, this is only implemented for local contracts.

To bypass this, you can call require on the original resolver which resides at `artificats.resolver.require()`! Example:

`artifacts.resolver.require("../lib/colonyNetwork/contracts/Authority", "../lib/colonyNetwork/build/contracts/");`

**Comment by ferittuncer** [comment]
@ConnorChristie I get `TypeError: Cannot read property 'require' of undefined` for `artifacts.resolver.require`

**Comment by amankakar** [comment]
this code
`const Contract = truffleContract(ReceptionsitFactory);
    Contract.setProvider(web3.currentProvider);
    const instanceFactory = await Contract.at(this.state.instanceFactory1);
   

    const newReceptionist = await Contract.at(this.state.instanceFactory1);

    await newReceptionist.createReceptionist(
      this.state.hospitalName,
      this.state.receptionistName,
      {
        from: this.state.accounts
      }
    );
gives me this error `
TypeError: address.replace is not a function

**Comment by gnidan** [comment]
Is this still an issue on Truffle v5? Thanks!

**Comment by amankakar** [comment]
No i have solved it.thanks!
