### ISSUE TITLE
Error: Cannot find module 'xhr2'

### ISSUE THREAD

**Issue by Niknakflak** [trufflesuite/truffle#478]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I was getting a weird error: 
![image](https://user-images.githubusercontent.com/5169683/27806686-d8c15964-5ff0-11e7-9324-ca9005ad9d5f.png)

so someone suggested I do a big reinstall of everything.
I uninstalled and reinstalled the following:

truffle
nodejs
npm

and then reinstalled them all.
After I did all of that, I attempt to compile and deploy contracts again and get hit with this error.
`Error: Cannot find module 'xhr2'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/truffle-config/node_modules/web3/lib/web3/httpprovider.js:38:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

and even if I specifically do an npm install of that module, running the same command: truffle deploy or truffle migrate gives the same error to much frustration.

## Steps to Reproduce

1. install node, npm, and truffle.
2. Get first error.
3. Uninstall node, npm, and truffle
3.5 (someone had me (npm cache clean --force) here
4. reinstall node, npm, and truffle
5. get second error
6. scream

## Expected Behavior

For the contracts to deploy the ropsten network

## Actual Results

Those errors appeared

## Environment

* Operating System: ubuntu 16.04.2
* Truffle version: Truffle v3.3.2 (core: 3.3.1)  Solidity v0.4.11 (solc-js)
* Ethereum client: Geth Version: 1.6.6-stable
* node version:  v8.1.3
* npm version:  5.0.3

**Comment by tcoulter** [comment]
Your first issue ("Invalid JSON RPC Response") is due to Truffle not being able to connect to your Ethereum client. Are you running the TestRPC? Please check your configuration and ensure your Ethereum client has the RPC service running on the same port. 

For the second issue ("xhr2"), this may be fixed in the latest version, 3.4.3. Can you update to the latest version and check to see if installation works properly? I'm going to close this ticket. Please open a new issue if you run into future errors.
