### ISSUE TITLE
Opcode listings should be in hexadecimal

### ISSUE THREAD

**Issue by wbl** [trufflesuite/truffle#4835]
Jump targets are identified by hex numbers, but the listing counts lines in decimal. This makes it tricky to see where the jump target is: you have to convert.

**Comment by haltman-at** [comment]
Sorry, what's the context for this?  There's a lot of information missing from this issue.  Is this about `truffle opcode`?  Or about the `p` display in `truffle debug`?  Or something else I'm not thinking of?

**Comment by Pobepto** [comment]
Hi @haltman-at, I want to help with this issue, but I don't quite understand the context. Can you explain a little more about what needs to be done?

**Comment by haltman-at** [comment]
Actually, this issue contains a misconception -- currently, `truffle opcode` doesn't print the instruction PC values, it prints the instruction *indices*!  Which is different, and much less useful... it should presumably print the PC and in hex, as @wbl says.

**Comment by haltman-at** [comment]
Sure, @Pobepto.  This issue pertains to the `truffle opcode` command, which acts as a disassembler.  Currently, it prints out each instruction prefixed with a number.  You might think (as @wbl did) that it's the PC value in decimal.  But actually, it's the instruction index in decimal.  (These can be different because `PUSH` instructions take up multiple bytes.  So if e.g. a contract starts with `PUSH1 0x80 POP`, then the `POP` instruction would have an index of 1 (because there's only one previous instruction) but a PC value of 2 (because there are two previous bytes).)

The instruction index isn't very useful; the PC value would be more useful, and it would be even *more* useful if, as @wbl requested, it were in hex, since that would allow one to see at a glance where jumps go.  So, to resolve this issue would mean changing that printout.

There is the question of if the old printout should be preserved in some form for those who want that (any opinion on this, @gnidan?) but I don't really see any value in the old way (and I believe `truffle opcode` is little-used anyway) so it's probably OK to just change it, is my guess?

Hope that explains things!

**Comment by gnidan** [comment]
> There is the question of if the old printout should be preserved in some form for those who want that (any opinion on this, @gnidan?) but I don't really see any value in the old way (and I believe truffle opcode is little-used anyway) so it's probably OK to just change it, is my guess?

I concur with this reasoning. If we can keep the existing info and still have the output look nice, then that's probably ideal, but I don't think it's a problem if we just get rid of the decimal instruction index info.

**Comment by Pobepto** [comment]
Thanks for explaining, @haltman-at! So, I'll get to work in the next few days. As soon as I have something ready I'll create pr.

**Comment by Pobepto** [comment]
@haltman-at, @gnidan Hi all, I prepared a PR - #4946. When you have time, take a look at it.

**Comment by eggplantzzz** [comment]
This has been released with version 5.5.8 https://github.com/trufflesuite/truffle/releases/tag/v5.5.8
