### ISSUE TITLE
Make the default subscriber for the dashboard more useful

### ISSUE THREAD

**Issue by MicaiahReid** [trufflesuite/truffle#4850]
The dashboard will need capability to listen to truffle events. We'll need to add a new default subscriber to truffle for the dashboard. A lot of other issues hinge on this capability.

**Comment by benjamincburns** [comment]
As I reread this ticket, I think I missed the underlying goal. The result from #4875 is a new default event subscriber, but that subscriber doesn't do anything to forward events off to the dashboard for consumption by the UI.

I think in order to support that we need a new message type to be added to the message bus specifically for transmitting Truffle event data. The problem for the moment is that truffle commands only communicate with the message bus via the RPC interface.

We could in theory funnel things through an extended RPC namespace, or we could make it possible for Truffle to detect via the RPC interface that it's talking to the dashboard, and have it connect directly to the message bus endpoint to publish event messages that way (assuming message publish is allowed at all via that endpoint).

**Comment by cliffoo** [comment]
> but that subscriber doesn't do anything to forward events off to the dashboard for consumption by the UI

That definitely doesn't happen by default. Perhaps when dashboard starts needing data from more Truffle events we can add some boilerplate, using a new message type as @benjamincburns suggested:
```ts
eventsThatTruffleNeedsDataFrom.map(e => ({
  [e]: [
    async (data) =>
      void (
        await this.messageBusClient.publish({
          type: "truffle-event-data",
          payload: { e, data }
          // There are other considerations like filtering to send
          // not `data`, only what is needed, but same idea
        })
      ).abandon()
  ]
}));
```
We are able to configure it! In my decoding in dashboard PR I'm [explicit about](https://github.com/trufflesuite/truffle/blob/95a094218a2c7a4983723bf9149f0ef34131940d/packages/events/defaultSubscribers/dashboard.js#L42-L52) which event to listen for (`compile:succeed`) and what to forward off to the message bus.
So the default subscriber _is_ useful in the sense that we can configure Truffle event listeners to forward data to the message bus client in the browser for an arbitrary purpose (e.g. consumption by UI, persist to db), which fits the bill.
Addendum: I prefer not extending rpc namespace for this unless there's a clear advantage in doing so.

**Comment by cliffoo** [comment]
Thanks @benjamincburns @MicaiahReid!
