### ISSUE TITLE
Dashboard shows odd network name when connecting with Ganache

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#5020]
## Issue

When I connect the dashboard to Ganache via Metamask, it tells me that I've connected to a network called "CENNZNET OLD."

## Steps to Reproduce

1. Start truffle dashboard
2. Configure MetaMask to point at localhost:8545
3. Observe network name shown in dashboard

## Expected Behavior

Network name should ideally be resolved in the following order (with each step falling back to the next):

1. User's `truffle-config.js`
2. Metamask's name for the network
3. https://chainid.network/chains.json (but pulled from the Truffle relay so we can unbreak old versions if that disappears/moves)

## Actual Results

![image](https://user-images.githubusercontent.com/803016/163287408-b1425d48-37a3-4b59-a770-4288f635c00d.png)

## Environment
 
* Truffle version (`truffle version`): v5.5.9

**Comment by haltman-at** [comment]
Note that the reason this is happening at present is due to the prioritization of (3) over the others (together with the use of chain ID 1337).

**Comment by cliffoo** [comment]
Some updates on this issue as I work through [pull#5241](https://github.com/trufflesuite/truffle/pull/5241).

In fear of potential supply chain attack (no hard feelings to [lists.eth](https://github.com/ethereum-lists/chains) or [defillama](https://github.com/DefiLlama/chainlist)), I'd like the new Dashboard to minimize all network requests that are not strictly related to processing Dashboard messages.

So chainid.network/chains.json appears to come from [ethereum-lists/chains](https://github.com/ethereum-lists/chains), and since:

- For a given chain, we only need its id and name for now.
- I'd like this id-to-name mapping to go into version control (like how we update sourcify fetcher).

I made a [little script](https://github.com/cliffoo/parse-chains) to parse the chain data in ethereum-lists/chains, which outputs a json small enough that I want to bundle it into the Dashboard frontend, and use like 
```js
import chainIDtoNameJson from "src/assets/chainIDtoName.json";
function getChainNameByID(id) {
  return chainIDtoName[id];
}
getChainNameByID(1337) // => "Ganache"
```

This, on top of my discovery that MetaMask doesn't seem to provide network names, I think the expected behavior can be modified as such:
Resolve chain name by:
1. `truffle-config.js`
2. `chainIDtoName.json` in `packages/dashboard/src/assets`

Note: [Here](https://github.com/cliffoo/parse-chains/blob/master/index.js#L15)'s why 1337 resolves to "Ganache".

**Comment by benjamincburns** [comment]
Open question (no bias from me toward yes/no here) - if we're considering bundling the network list in with the dashboard that will mean that old versions will never "discover" new network configurations. Do we care about that? Perhaps we could make that JSON object something that could be fetched periodically?
