### ISSUE TITLE
Can't publish a version lower than latest version to ethpm

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle#511]
I don't know if this is the right place to report this, but I couldn't find a canonic ethpm repo.
 
OpenZeppelin ethpm package: https://www.ethpm.com/registry/packages/25

Trying to publish v1.1.0

```
$ truffle publish
Gathering contracts...
Finding publishable artifacts...
Uploading sources and publishing to registry...
Error: Could not publish package. Please check version number and ensure it was not previously published.
    at /home/maraoz/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:130139:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

Is this expected behavior? why?

**Comment by tcoulter** [comment]
Yep! You've already published 1.2.0! What's the reason for wanting to publish an older version? 

@pipermerriam Was there a security reason here? My spidey senses say so, but I forget.

**Comment by maraoz** [comment]
Yes, we had versions 1.1.0 and 1.2.0 on npm and wanted to update ethpm, and started with 1.2.0

**Comment by pipermerriam** [comment]
I'm trying to recall the *why* and I'm coming up blank.  The general idea was that packages shouldn't be back-filling releases.  I understand this specific case is not backfilling as much as just pushing an existing release to a new index.  Unless I get a *eureka* moment and figure out a security reason for this I'm fine relaxing the restriction to one of.

* Removal of the restriction all-together
* Require something explicit to backfill in this manner since it should always be a special case.

**Comment by pipermerriam** [comment]
@maraoz the latest evolution of EthPM abandons the centralized registry in favor of a federated model.  We have no intentions of maintaining the existing registry and will likely get that site taken down and replaced by something else soon.

**Comment by gnidan** [comment]
Oh hey @pipermerriam, thanks for the response!

Gonna close this now. Will have more word on Truffle's upcoming EthPM integration once the EthPM v2 work settles. Thanks!

**Comment by maraoz** [comment]
@pipermerriam sounds good! thanks for the heads up :)
