### ISSUE TITLE
contract deployed but still getting undefined in truffle console

### ISSUE THREAD

**Issue by pbirbarah** [trufflesuite/truffle#5168]
### Discussed in https://github.com/orgs/trufflesuite/discussions/5167

<div type='discussions-op-text'>

<sup>Originally posted by **pbirbarah** June  2, 2022</sup>
I have downloaded truffle extension in visual studio and also downloaded ganache. I was able to deploy a contract on ganache (used truffle migrate successfully) but when I use the truffle console to get info about the contract like const bla = await contract.deployed() I get undefined, can't figure out why
![ganache pic](https://user-images.githubusercontent.com/74081842/171734192-573364f3-446b-476b-ae49-aee8e2ac9fa4.PNG)

</div>

**Comment by haltman-at** [comment]
Well, note that `const bla = await contract.deployed()` will return `undefined` due to the fact that it's a statement, rather than expression, but that doesn't mean that `bla` itself is undefined; if you enter `bla` afterward, you should see it defined.  Can you confirm whether it works?

(Also, if you simply write `bla = await contract.deployed()`, then since that's an expression, it ought to return the value assigned to `bla`; unfortunately, due to issue #3349, currently this will also display `undefined`.  However, even here, the assignment *does* still occur, and if you enter `bla` afterward, you should see it defined.  Again, can you confirm whether this works?)

Thanks!

**Comment by pbirbarah** [comment]
Ok thanks!! It worked!
