### ISSUE TITLE
Windows fails to run truffle whereas successfully installed it

### ISSUE THREAD

**Issue by Kakap0** [trufflesuite/truffle#542]
OS: Windows Server 2012 R2
node: v8.4.0
npm: 5.3.0
I'm working under a corporate proxy.

## Issue

Hi, I'm following David Burela's tutorial to install testrpc and truffle on Windows [https://davidburela.wordpress.com/2016/11/18/how-to-install-truffle-testrpc-on-windows-for-blockchain-development/] . Everything seems to work fine until  I call truffle.

![capture](https://user-images.githubusercontent.com/31247304/29571814-8fca00da-875a-11e7-8efa-af91c66e41d3.png)

## Steps to Reproduce

npm install -g npm
npm install -g -production windows-build-tools
npm install -g ethereumjs-testrpc
npm install -g truffle

## Expected Behavior

The list of truffle's commands.

## Actual Results

![capture1](https://user-images.githubusercontent.com/31247304/29571824-9754ac24-875a-11e7-8a73-623aaa837b86.PNG)

Any idea of what I did wrong and how to fix it?

I'm a newbie do not hesitate to tell me if I forgot any needed information. I would be gratefull for any help provided.

**Comment by tcoulter** [comment]
Hi there. This usually indicates a problem with your PATH environment variable. How did you install Node.js? If you used the Windows installer, it should have configured your PATH correctly.

Sometimes, after installing new software on the command line, new tools won't be registered unless you restart the command prompt. Try that first and let me know if it works for you.

I'm going to close this ticket, assuming you were able to find a fix (since this ticket is a month old). If not, please open a new ticket and reference this one.

Cheers!
