### ISSUE TITLE
Blank Dashboard HELP!

### ISSUE THREAD

**Issue by Josip230** [trufflesuite/truffle#5499]
## Issue
I'm trying to create Nft Collection But my truffle dashboard is blank Please help

* Operating System: 
* Windows
* Truffle version (`I've just ran install truffle`):
* node version (`idk`):
* npm version (`idk`):

**Comment by gnidan** [comment]
Hm this keeps happening to some users periodically. Unfortunately the team is out of office this week and we can't help diagnose this until we return.

In the meantime, please make sure you have MetaMask installed, or maybe try a different browser (also with MetaMask)

**Comment by cliffoo** [comment]
Hey @Josip230. On top of trying different MetaMask-enabled browsers as @gnidan mentioned, can you run `truffle version` and see what version of Truffle you have?

**Comment by cds-amal** [comment]
Hi @Josip230, sorry to add another environment request, but it will help us understand this issue. 

- What version of windows are you using? 
- Do you have developer mode enabled? 
- Do you use WSL v1, or WSL2?

Thanks in advance.

**Comment by cliffoo** [comment]
Ah you might want to look elsewhere then. Solana has their own tooling, and Truffle has no support for it at the moment.

But... Check out our [nft marketplace tutorial](https://trufflesuite.com/guides/nft-marketplace/) since you have Truffle installed anyway?

Also it'd still be very helpful for us if you could kindly provide more info about your setup (Is it still blank after you installed MetaMask? What browser? Truffle version? Windows version? Developer mode? WSL1 or 2?)

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance, but let us know if there's still a problem here!
