### ISSUE TITLE
npx truffle init does not create Migrations.sol

### ISSUE THREAD

**Issue by cuongrep** [trufflesuite/truffle#5532]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

I hope that the Migrations.sol file will be automatically generated when we initial a new solidity project using truffle.

## Actual Results

When I create a new solidity project using truffle command "npx truffle init". I found that no any Migrations.sol file is created

## Environment

* Operating System: macOS
* Ethereum client: 
* Truffle version (`truffle version`): v5.5.29
* node version (`node --version`): v16.16.0
* npm version (`npm --version`): 8.7.0

**Comment by sukanyaparashar** [comment]
Hello @cuongrep. Thanks for bringing this up. Truffle has removed the inclusion of `Migration.sol` on `npx truffle init` command since `v5.5.27`. Now when you run `npx truffle init`, it includes the following -

- an empty `contracts` folder.
- an empty `migrations` folder.
- an empty `test` folder.
- a `.gitignore` file.
- a `truffle-config.js` file.

Please let us know if this information is helpful.

**Comment by gnidan** [comment]
Maybe we should make it an option for `truffle init`, like `truffle init --with-migrations`. But yeah honestly I recommend never using on-chain migrations.

**Comment by matteo-dirollo** [comment]
truffle unbox works fine for me

**Comment by cliffoo** [comment]
Closing for issue maintenance.

**Comment by MontahaBouziri** [comment]
i'm having the same issue here
