### ISSUE TITLE
Feature request: running migrations for dependencies

### ISSUE THREAD

**Issue by cag** [trufflesuite/truffle#554]
It would be nice if one could specify dependencies for which migrations are run when the project's migrations are run. For example, suppose there is a framework written in Solidity which requires certain contracts to be deployed. A project using that framework might specify its use using NPM or EthPM.

In a different project, maybe there is a configuration key which specifies the dependency migrations for which this project's migration depends. Basically, Truffle will `truffle migrate` those dependencies automatically before running the project's dependencies, and in the case of the aforementioned example project, the framework's migration will be run first.

I dunno whether it would be better to require all dependencies including child deps to be specified in order, or whether the deps should be toposorted and migrated in that order.

**Comment by cag** [comment]
I've started a branch where this might take shape: https://github.com/cag/truffle/tree/migrate-deps

**Comment by cgewecke** [comment]
@cag No no no. Completely deferring to your good judgement here. We were talking about this this morning and thought that you're probably in the best position to know what's needed because you have a real use case. 

I'm just eventing out the migrations so that they can have reporters and be made interactive, more informative, etc. And use async/await more intuitively.  

This work sound quite close to artifact level stuff that @gnidan is working on, which inevitably touches migrations. . . 

Anyway awesome! Thank you.

**Comment by cag** [comment]
Alright, I am _almost_ there, but everything is usable already, so I am putting it out, but please wait a bit before you start reviewing those PRs. Things could still use a bit of polish, and the test case for running tests fails (it is run before the migration test so that it won't produce passing-like behavior, as it should).

**Comment by cag** [comment]
Hey, it is done, and you can try it out with

```bash
npm install --save-dev cag/truffle#migrate-deps-build
```

**Comment by cgewecke** [comment]
@cag Ok awesome! Will  check this out this week . . .

**Comment by cgewecke** [comment]
Hi @cag oh cool!

I'm lagging really bad here sorry - I wanted to leave you a note because there's a bit of chaos coming down the line this week: 
+ we're moving the whole `truffle` project back into one repo (using Lerna, on wednesday). As part of that - I'm going to merge all of your work into staging branches that will carry over into the new format.
+ we're planning a beta release for Truffle V5 at the end of the month, and was thinking that this work would ultimately target that branch (next). Are you ok with that? V5 will have some breaking changes because it upgrades web3 - might be kind of annoying. But your changes also fit really well with the Migrations rewrite which is part of it.
+ Finally, there are some files where there will be conflicts - as soon as the ongoing migrations work is merged into next here, I'm going to resolve those and get this stuff re-opened as a single PR and ping you. 

Sorry about the mayhem and thanks so much this work -  it's going to be really really cool to have this.

**Comment by cag** [comment]
Hey, no problem! Yeah SGTM.

**Comment by haltman-at** [comment]
Reopening this, as this was never completed.

**Comment by haltman-at** [comment]
Note that @cag currently has a PR open to address this, #1511, but it's badly out of date and progress on it seems to have stalled.  Need to determine what to do here.

**Comment by cag** [comment]
I'm guessing that it'd be easier to just start from scratch with new
branches at this point, though if somebody wants to rebase/merge the stuff
I did, feel free to do so. Hopefully the work done in the PRs make sense
and help, but if they don't, 🤷
