### ISSUE TITLE
Allow the Dashboard host and port to be configurable when using the Dashboard Hardhat Plugin

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/truffle#5958]
## Issue

When using the Truffle Dashboard Hardhat Plugin, the target [host and port are currently hardcoded](https://github.com/trufflesuite/truffle/blob/develop/packages/dashboard-hardhat-plugin/src/index.ts#L23-L26) to the defaults (`localhost` and `24012` respectively). As highlighted in [this conversation](https://github.com/trufflesuite/truffle/pull/5927#discussion_r1122179058) this should be made user configurable by allowing users to specifying them in the Hardhat config.

**Comment by gnidan** [comment]
You know what I just realized... maybe there's a way for this plugin to remove the need for the user to define the dashboard network themselves. Can HH plugins define networks... is that kosher?

Ooh yeah OK I think we should probably read up on how [hardhat-foundry](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-foundry) works and just emulate that.

**Comment by gnidan** [comment]
Did some more digging on the above and chatted with @alcuadrado, who confirms the limitation I describe here.

So I really want this sort of thing:

<details>
<summary>Example <code>hardhat.config.ts</code></summary>

```typescript
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "@truffle/dashboard-hardhat-plugin";

const config: HardhatUserConfig = {
  networks: {
    "truffle-dashboard": {
      timeout: 60 // override **only** the default timeout in seconds
    },

    // ... rest of HardhatNetworksUserConfig
  },

  truffle: {
    dashboardNetworkName: "truffle-dashboard"
  },

  // ... rest of HardhatUserConfig ...
};

export default config;
```

</details>

i.e., the plugin should minimize the configuration options it adds in that `truffle` namespace. Instead, we should allow people to override the Dashboard network the same way they would override any HTTP network in their Hardhat config. This plugin should then fill in the gaps between Hardhat's defaults and the user-specified network params.

It's worth noting here that the way Hardhat does config is by separating user config from complete config with defaults. It defines types for the `HardhatUserConfig` (e.g. `HttpNetworkUserConfig`), where most fields are optional, and it has separate types for the `HardhatConfig`, where everything is filled in. Key points here:

- Plugins have the chance to read the user-config and modify the config however they want. So we can add a network just fine.
- Hardhat generates the config from the user-config **before** plugins run. _This importantly includes validation._

The problem with my example is that Hardhat does this:
1. Attempt to validate that network with the `timeout` property.
2. Try to interpret it as a [`HttpNetworkUserConfig`](https://github.com/NomicFoundation/hardhat/blob/9fa977b4a7416f9c6466541144abc495b5c732a4/packages/hardhat-core/src/types/config.ts#L100-L110).
3. Observe that `url` is missing and fail.

Presumably this fails because there's no good default value for Hardhat to use for `url` in the output [`HardhatNetworkConfig`](https://github.com/NomicFoundation/hardhat/blob/9fa977b4a7416f9c6466541144abc495b5c732a4/packages/hardhat-core/src/types/config.ts#L183-L193), and Hardhat isn't architected to consult plugins for missing network configurations.

Now, we can _add_ a fresh network just fine, but if we want users to override this Truffle Dashboard network, I can think of two options:
- Force users to supply a blank `url: ""` property, which the plugin would overwrite, or,
- _Completely manage_ the Dashboard network and have users configure specific properties somewhere outside the usual `userConfig.networks[networkName]` object.

With the latter option, we're looking at something like this:

<details>
<summary>Less ideal example <code>hardhat.config.ts</code></summary>

```typescript
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "@truffle/dashboard-hardhat-plugin";

const config: HardhatUserConfig = {
  networks: {
    // ... entire HardhatNetworksUserConfig
    // !! MUST NOT INCLUDE THE TRUFFLE DASHBOARD NETWORK !!
  },

  truffle: {
    dashboard: {
      networkName: "truffle-dashboard",
      timeout: 60
    }
  },

  // ... rest of HardhatUserConfig ...
};

export default config;
```

(_I'm back to thinking we need a `truffle: { dashboard: { } }` namespace, but please someone convince me otherwise!_)
</details>


Not ideal. I'm thinking this approach is probably still not terrible... it still seems nice for @truffle/dashboard-hardhat-plugin to supply the network config itself.

But... will lots of people want to configure the timeout or other settings? I was going to suggest default to just disable the timeout altogether for this network, but seems like opinions could easily differ for that (and other settings like `gasMultiplier`). Bit annoying for these settings to live inside this other `truffle.dashboard` namespace.

As a small consolation, we _can_ control whether the plugin does this network management by adding a `truffle.dashboard.manageNetwork: boolean` property, so there's a trivial way to offer an "eject button" to the old/plugin-less behavior.

**Comment by gnidan** [comment]
This is now done!

@truffle/dashboard-hardhat-plugin supports customization starting in v0.2.0 of that package.
