### ISSUE TITLE
A docker tutorial to help beginners

### ISSUE THREAD

**Issue by gregbkr** [trufflesuite/truffle#610]
Hello Truffle team,

Not sure who to contact, but if it can help the community, here is a step by step github [guide](https://github.com/gregbkr/geth-truffle-docker) and [blog](https://greg.satoshi.tech/deploy-your-first-smart-contract-with-this-base-ethereum-truffle-setup/) on how to use Geth+Truffle in docker, and how to deploy and interact with few easy smart contracts (greeter, metacoin, counter). 

I am maintaining it for the Geneva Dev [meetup](https://www.meetup.com/Geneva-DevChain-UserGroup/) team, where we on-board new comers every months. 

Feel free to close this issue.

Thank you for any feedback and very good week!
Keep up the good/awesome work! 
Greg.

**Comment by earizon** [comment]
(Related)

I use next script to wrap truffle in a containerized environment:
`https://github.com/earizon/utility_shell_scripts/blob/master/node_wrapper.sh`

First I install in a local directory as:
`$ ./node_wrapper.sh npm install -g --prefix=/root/truffle_install truffle`

Then on the working directory I create a second utility script (just to save some typing):

    $ cat truffle.sh 
    #!/bin/bash
    ./node_wrapper.sh /root/truffle_install/bin/truffle $*

Finally I just execute `./truffle.sh <command>` instead of just `truffle <command>`

The node_wrapper.sh is really simple. The node version can be changed by just modifying the value of `NODE_VERSION`. This script can be used as a final utility or as a reference for more elaborate setups
