### ISSUE TITLE
Ensure all official Truffle Boxes are compatible with Truffle 4

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#634]
As part of the upcoming Truffle 4 release, the Truffle Boxes should be updated for latest versions of Solidity and not produce warnings in the common workflows.

(Related: #628 #604)

**Comment by tcoulter** [comment]
Quick note: Tutorial token contracts show warnings for Truffle 4.0: 

![screenshot 16](https://user-images.githubusercontent.com/92629/32242869-177ec530-be31-11e7-9e98-c63cbed70902.png)

**Comment by agrcrobles** [comment]
In order to learn a little bit more about truffle, in some free time I created [react-ethereum-metacoin](https://github.com/agrcrobles/react-ethereum-metacoin) which is compatible with truffle 4 and I will be happy to add it to be used as a box.

That's all, thanks for maintaining and supporting this awesome set of libraries. :)

**Comment by gnidan** [comment]
Outdated, closing
