### ISSUE TITLE
artifacts - does not recognized by IDE in tests

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [trufflesuite/truffle#672]
Hello, for some reasons webstorm IDE does not see truffle keywords.

**Comment by mbrennan** [comment]
I'm having the same trouble.  I'm not sure how to get the IDE to recognize those symbols.  I'm using intellij-solidity.  I doubt this is any problem with truffle, but I wonder if there is some package that could be developed so Intellij-based IDEs can recognize these symbols.

**Comment by tcoulter** [comment]
Hi there,

We'd love an Intellij plugin! to my knowledge though we don't have one. Would love to see one made by the community.

I'm going to close this ticket for housekeeping purposes, and because supported Intellij may not officially be on our radar for quite some time. Let me know if you have questions.
