### ISSUE TITLE
Unable to send ether in testcase

### ISSUE THREAD

**Issue by tillkolter** [trufflesuite/truffle#715]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Minimal contract:

```
contract Payable {
    function Payable() public payable {
    }
}
``` 

Testcase:
```
import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Payable.sol";

contract TestPayableContract {
    function testCreatePayableContract() {
        address payableAddress = new Payable().value(1000);
        Assert.equal(payableAddress.balance, 10000); 
    }
}
```

## Expected Behavior

Testcase completes successfully.

## Actual Results

```
TypeError: Member "value" not found or not visible after argument-dependent lookup in contract Payable - did you forget the "payable" modifier?
        new Payable().value(1000);
```

## Environment

* Operating System: Mac OS X 10.13.1
* Truffle version: Truffle v4.0.1 (core: 4.0.1), Solidity v0.4.18 (solc-js)
* Ethereum client: Truffle develop
* node version: v7.5.0
* npm version: 4.1.2

**Comment by JackPickering** [comment]
A few things:
You should be using a test case - look up testing on truffle docs for this 

Inside an "it" case you should then specify the deployed contract:

var myContract = Payable.deployed();

You can then transfer a payment to the contract like so: 
myContract.call({value: web3.toWei(0.5, "ether"), from: accounts[1]}); 

This would send 0.5 ethers to your contract from the first account in the dev blockchain

**Comment by JackPickering** [comment]
You also havent specified a balance, so create a balance (uint256 balance;) and then in your payab;e function add the amount received (msg.amount) to the balance stored and then check it in the testcase like so: 

balance = myContract.balance();

**Comment by cgewecke** [comment]
Hi @tillkolter. This is an interesting issue. Thanks for opening and apologies for the delay in responding. (There's more on this topic in the [advanced features section](http://truffleframework.com/docs/getting_started/solidity-tests#advanced-features) of the Solidity testing docs.) 

Truffle does some magic behind the scenes of the Solidity tests to make ether available in the Test contracts. If you declare a `uint public initialBalance` at the top of any test, you'll be able to fund other contracts and send eth around as shown below. 

Your specific question related to funding a contract on creation and that case is covered last in this example - but have included some other `send` cases for clarity.

If we have a `Payable` contract:
```javascript
contract Payable {
    function Payable() public payable {
    }
}
```
We can write the following test:
```javascript
pragma solidity ^0.4.18;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Payable.sol";

contract TestMetacoin {
  
  // Truffle looks for `initialBalance` when it compiles the test suite 
  // and funds this test contract with the specified amount on deployment.
  uint public initialBalance = 10 ether;

  function testSendingEther() public {
    
    // The `this` contract (e.g. TestMetacoin) should have a 
    // starting balance of 10 ether 
    Assert.equal(this.balance, 10 ether);
  
    // A new Payable contract has a zero balance
    address pay = new Payable();
    Assert.equal(pay.balance, 0);
    
    // Send `pay` 5000 wei (it's being sent by `TestMetacoin`).  Wei is the default
    // denomination in Solidity if you don't specify another unit 
    pay.send(5000); 
    Assert.equal(pay.balance, 5000 wei);

    // We can also fund a contract on creation. Solidity's syntax for this is a 
    // little unusual :) If the `Payable` contract's constructor took arguments, 
    // they would go in the final parentheses attached to the new expression.
    address anotherPay = (new Payable).value(1 ether)(); 
    Assert.equal(anotherPay.balance, 1 ether);
  }
}
```

Closing for house-keeping because Truffle's solidity-testing ether mechanism appears to be working correctly. Thanks again for raising this question.

**Comment by shredding** [comment]
I get ` TypeError: crowdsale.call is not a function` (where crowdsale is the instance gotten from `crowdsale = await SampleCrowdsale.deployed()`. 

Why's that?

**Comment by AlvaroLuken** [comment]
Just as a note this works only if you hardcode 10 ether - it gives a pretty wild error if you input any other amount :+1:
