### ISSUE TITLE
Provide the ability to disable all timeout limits for `truffle migrate` script

### ISSUE THREAD

**Issue by krabradosty** [trufflesuite/truffle#718]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
For low gas price `truffle migrate` ended with a timeout error. I set low gas price (6 Gwei) because my contracts need about 8*10^6 of gas. I can wait for a couple of hours for contracts deploying, it's OK for me. I find this line in the truffle-contract module:

`var timeout = C.synchronization_timeout || 240000;`

## Steps to Reproduce

set low gas price in truffle network configuration

## Expected Behavior

all contracts are deployed

## Actual Results
The error occurred during `truffle migrate`: "Error: Transaction 0x... wasn't processed in 240 seconds!"

## Environment

* Operating System: ubuntu 16.04
* Truffle version: 4.0.1
* Ethereum client: infura mainnet
* node version: 8.2.1
* npm version: 5.3.0

**Comment by krabradosty** [comment]
After I fixed timeout to be 0 (just set timeout in the`/node_modules/truffle/build/cli.bundled.js`), I got another error during running migration script with a low gas price: `Contract transaction couldn't be found after 50 blocks`.

**Comment by cgewecke** [comment]
@krabradosty Thanks for identifying that bug! It's fixed in the latest release. 

Unfortunately, while looking into this issue, it's been discovered that that `web3` has it's own hardcoded wait limit: 50 blocks. (Code [here](https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L105-L115)). 

For the moment anyway, to be mined via `web3` (which Truffle uses), you'll have to set your deployment gas price high enough to get picked up within 50 blocks.

Closing, thanks for your help!

**Comment by leberknecht** [comment]
For the logs: 
This is the way to change `synchronization_timeout`:
```
const MyContract = artifacts.require('./CrossLendBond.sol');
MyContract.synchronization_timeout = 42; //timeout in seconds
```
