### ISSUE TITLE
Specify order of truffle tests

### ISSUE THREAD

**Issue by JackPickering** [trufflesuite/truffle#741]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Why cant we specify an order in which we'd like our test files to be executed? I found a closed issue which reads 'because test files shouldn't depend on each other' which just isn't true. 

They may not depend on each other but they may depend on other factors i.e. I have 4 files A,B,C,D.

A, B, C and D all require start times in the form of a timestamp.  

File A has 4 stages which are 1 day in length, to test this file I must test each stage, to test each stage I must 'time travel' to the next stage (by making my dev blockchain think its mined a days worth of blocks). 

Now that I have tested each stage I am 4 days in the future. 

How do I now test file B if the I have to specify a timestamp as to when this will be? 

As if I attempt to set a timestamp to 4 days after file A was meant to have started and file C 4 days after that, Truffle could run the test files in a random order and run C, B then A which would mean my timestamps for each instance are now incorrect and throw an invalid opcode error. 

Test files may not be dependent on each other, but as they are depending on a common development chain I believe it is necessary to be able to order them on demand.

**Comment by chuacw** [comment]
Use evm_increaseTime to set or increase the current time to a point in future.

**Comment by JackPickering** [comment]
I do that, but my problem isnt with increasing time, its not knowing which test will run first (i.e. if could test A in month 1, B in month2, C in month 3 and D in month 4) 

But to make sure each test only lasts 1 month and the stages work correctly, I must specify a time stamp for the start of each sale, i.e. 
A = January 1st
B = February 1st
C = March 1st
D = April 1st

What do I do now if my tests run in reverse order? D wont start for 4 months and by the time it gets to test 1 it will have increased time 4 times to month 4 therefore A would have finished failing all of my tests.

**Comment by JackPickering** [comment]
I got round this by changing my contract to start the sales on the 'latest' block in the chain. But seen as though I have to change my contract to suit the tests I feel like this is a quick fix issue which can be fixed by a simple configuration specification in order to allow people to specify in what order the test files are ran...

**Comment by chuacw** [comment]
Well, you can name your files with a 1-digit numeric prefix, if you have less than 10 files, in ascending order of execution.
eg, 1_this_first.js, 2_next.js, etc.

They will be executed in that order, the file with the lowest numerical prefix will be executed first.

**Comment by JackPickering** [comment]
Thats what it used to do, but it not longer does that, I have 1_, 2_, 3_ prefixes before my filenames and it still executes in random order

**Comment by JackPickering** [comment]
All of these are still quick fixes to a seemingly simply change on Truffles end

**Comment by SCBuergel** [comment]
>They will be executed in that order, the file with the lowest numerical prefix will be executed first.

@chuacw our tests are being executed in arbitrary order and that order changes from one test to another. IMO integration tests with complex dependencies are surfacing a lot more crucial issues than simple unit tests and therefore this feature would be highly relevant for smart contract security in general.

**Comment by cgewecke** [comment]
@JackPickering @SCBuergel - Have looked around Stack Overflow a bit and it seems like the consensus is:
+ mocha executes files serially
+ on linux and mac it executes them in alphabetical order
+ on windows, that order isn't guaranteed, but mocha has a [`sort` option](https://mochajs.org/#usage) for files. Mocha can be configured in `truffle.js` (example at Gnosis [here](https://github.com/gnosis/gnosis-contracts/blob/master/truffle.js#L42-L46))

That said, it's possible tests executing in arbitrary order might be caused by not returning promise chains to Mocha / not using the `done` method. 

@JackPickering - could you see if this problem goes away if you return `.then` promise chains like this in [Capped_ICO](https://github.com/JackPickering/Capped_ICO/blob/master/test/7Crowdsale_Stages_Test.js#L119-L129)  as below? This step doesn't need to be taken for async / await tests. 

```javascript
it('executes serially', function(){
  return myAsyncMethod().then(function(){
      return anotherAsyncMethod().then( .... etc .. 
})
``` 

[Guide](http://tobyho.com/2015/12/16/mocha-with-promises/) to promises in Mocha.

**Comment by SCBuergel** [comment]
Thank you for providing all these insights @cgewecke.

> on linux and mac it executes them in alphabetical order

No, I'm on mac and the order seems to be random at times (it is mostly ok, hard to reproduce when it's not).

> That said, it's possible tests executing in arbitrary order might be caused by not returning promise chains to Mocha / not using the done method.

I always break all my fingers when working with promises, hence I'm doing async/await. Maybe that adds to the problem.

**Comment by cgewecke** [comment]
@SCBuergel Thanks for the kind words. I don't think my analysis is correct on reflection. Dropped promises shouldn't change the execution order of the suites - they should just result in the test executing synchronously. The only relevant case I've seen in the issues at mocha is where someone makes their describe an async function, which could happen by accident. This merits more investigation . . .

**Comment by cgewecke** [comment]
@JackPickering If you could point me in the direction of a public repo where this problem is reproducible it would be helpful. At the moment when I look around at various  projects in CI that use Truffle 4 I see all their tests running in strict alphabetical order (on Linux) without variance.  See [zeppelin-solidity](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/jobs/324185757).

If your project is private, could you check to see whether you have accidentally defined any `describe` blocks within the tests as `async function`? Thanks!

**Comment by cgewecke** [comment]
I've looked some more and I'm not seeing this in the CI records of any other Truffle projects that use Truffle 4. So, reluctantly closing but please re-open or ping here if anyone has a reproducible case.
