### ISSUE TITLE
Cannot find import Pausable.sol from ClockAuction.sol in npm scripts

### ISSUE THREAD

**Issue by doubaozia** [trufflesuite/truffle#772]
## Issue
`{
"migrate": "rm -rf build/contracts && truffle migrate --network development"
}`
when i run npm run migrage like above, the terminal give me the errors:
`Error compiling:

Cannot find import Pausable.sol from ClockAuction.sol. If it's a relative path, ensure it starts with `./` or `../`
but when i just run rm -rf build/contracts && truffle migrate --network development it works.`
## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

the script run successful and the contracts migrated.

## Actual Results

show errors about the path,see above.

## Environment

* Operating System: macOS Hign Sierra 10.13.2
* Truffle version: v4.0.5
* Ethereum client: Ganache
* node version: v8.9.4
* npm version: v5.6.0

**Comment by cgewecke** [comment]
@doubaozia This looks like an issue that might be related to the execution context of your script rather than a bug Truffle can address per se. Closing this for house-keeping since it doesn't seem like other people are running into this issue and there are many options for automating commands in the shell.
