### ISSUE TITLE
truffle init deletes existing readme.md file

### ISSUE THREAD

**Issue by marcpre** [trufflesuite/truffle#786]
---------------------------

## Issue

When doing the `truffle init` command, if there is an existing readme.md file it gets deleted

## Steps to Reproduce

Create Repository on github and clone it with the pre-existing readme.md file. Then install truffel and run `truffle init`.

## Expected Behavior

I expect that truffle only adds folders/files and does not delete any folders or files.

## Actual Results

Truffle deleted the readme.md file

## Environment

* Operating System: Ubuntu 14.04.5 LTS
* Truffle version: 4.0.5
* Ethereum client: Ganache-CLI
* node version: v6.11.2
* npm version: 3.10.10

**Comment by TedtheDev** [comment]
Hi. I have been poking around the code and trying to figure out why the README is getting deleted. I figured I would give this a shot since it is just deleting a file. 

The 'init' command is using 'bare-box'. https://github.com/truffle-box/bare-box/. In the truffle-box.json ignore property, it has README as one of the files to ignore (delete). First, yours gets overwritten by this one (I think) and truffle deletes it anyway when it is cleaning itself up.

What you should do to avoid this is instead of creating a README first, run truffle init and then add a readme AFTER init. Another way you could avoid this issue is to rename your current README to something else like README_MINE and then run init. Finally, delete the truffle README and rename yours back to README. Voila! 

Let me know if that works.

**Comment by marcpre** [comment]
Thx for your reply! 

This is definitely working. I think the expected behavior should be:

## Expected Behavior

I expect that truffle only adds folders/files and does not delete any folders or files.

**Comment by lazaridiscom** [comment]
@marcpre 

I understand you expectation. Yet, `init` has the meaning of `from scratch`, and thus it should be expected that `everything starts from zero`.

## Suggestion

```
if destinationFolder exists:
  warne "All files within the destination folder will be overwritten, proceed?"
```

**Comment by marcpre** [comment]
I like your suggestion. 

However, I think if you still have to accept each warning this would hinder your development workflow. I would add these warnings but if you add f.ex. the `-f` flag your folders will be added and nothing gets overwritten. Similiar to `npm init -f`, when your `package *.json` just gets created by default.

**Comment by lazaridiscom** [comment]
Sounds rational. So, i guess the relevant suggestion would be:

=> adopt `npm init` `-f` flag behavior

and the overall suggestion would be:

=> Align truffles's cmd-line options and behavior to known tools (npm)

**Comment by TedtheDev** [comment]
The flag is a good idea, but I saw some code where you can't put anymore option on the init command. It looked like you could base which box you wanted to init with.

Perhaps another suggestion is to only delete/reset necessary files related to a truffle project. For example, don't delete anything if there is any readme or other folders/files not related to truffle. 

Say you have a readme file, a folder named 'styles', a file named 'helloworld.js', another folder named 'contracts', a 'truffle.js' file, and 'truffle-box.js'. In theory, I would think it wouldn't delete the readme, folder named 'styles' and a file named 'helloworld.js', but it would delete and reset truffle.js, truffle-box.js, and the 'contracts' folder, etc because you are starting from scratch.

**Comment by lazaridiscom** [comment]
@cgewecke , seeing #785 i realized the "uses current directory" behavior. This should be changed immediately, `truffle init x` should create folder `x`, like any other tool does.

**Comment by cgewecke** [comment]
@lazaridiscom Agree there's is a good case for modifying this although it will also require further discussion. Among other things it would be a consequential change within the Truffle codebase which uses the box mechanism for some of its E2E testing. And we'd need to see if there are other implications, would this break things outside Truffle?

**Comment by lazaridiscom** [comment]
this one line says it all "truffle unbox metacoin pastes contents in current directory, expected to mkdir".

So, this would have 2 steps:

- decide if something was done wrong, and that this **must** be reversed
- decide **how** to reverse this, to avoid as much as possible breaking things

Sometimes, its just not possible to avoid breaking things. Its a matter of priorities, and I think the top priority is to comply to the `unwritten standards` of tools

**Comment by cgewecke** [comment]
4.0.7 contains a patch for this. If a folder has contents, truffle will no longer unbox into it. Thanks for reporting!
