### ISSUE TITLE
Error: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by freshonline** [trufflesuite/truffle#802]
Error:
===================
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: insufficient funds for gas * price + value
=======================
geth:
==========================
geth --rpc --port 30304 --rpcport 8599 --targetgaslimit 9000000000000 --rpcapi db,eth,web3,net,admin,miner,personal --cache 1024 --maxpeers 25 --datadir /home/testnet/.ethereum --keystore /home/testnet/.ethereum/keystore --nousb --fast --testnet --mine --minerthreads 1 --unlock 0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66 --password /home/testnet/pass
================================
truffle.js
====================================
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8599,
      network_id: 3,
      from: "0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66",
      gas: 1000000,
      gasPrice: 10000000000,
    }
  }
};
===============================
Why?
I have balance in "0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66".

**Comment by lazaridiscom** [comment]
@freshonline , hop over to [Truffle Gitter](http://gitter.im/Consensys/truffle), there you should get help faster

**Comment by cgewecke** [comment]
@freshonline Agree with @lazaridiscom - this is a good question to raise on Truffle's gitter.

Could you try raising the value of `gas` in your `truffle.js`. It's limited to `1,000,000`. The error suggests at least on of your contracts requires more than that to deploy. Could you also try testing your migrations with `ganache-cli` to verify they're successful against a test blockchain? 

Closing this because you haven't filled out any of the issues template - we'd need a lot more context and information to evaluate this issue as a bug.

**Comment by cgewecke** [comment]
@freshonline Apologies - I see you've opened another issue with more detail - will address there.
