### ISSUE TITLE
[DEV] Experiences with Multi-Repo Development (meta)

### ISSUE THREAD

**Issue by lazaridiscom** [trufflesuite/truffle#835]
https://github.com/trufflesuite/truffle/blob/develop/CONTRIBUTING.md#forks-branches-and-pull-requests

The above describes your development-setup, where you can checkout easily inter-related repositories.

How are your experiences with this? I am mainly interested in the daily production flow, especially when e.g. changes are across multiple repos.

Is it really as easy as its described?

**Comment by cgewecke** [comment]
@lazaridiscom I found it intimidating at first but it works beautifully. Is also critical for CI on a project organized this way. @gnidan set it up.

**Comment by lazaridiscom** [comment]
I saw another solution, which checks out the repos into the `node_modules` folder, but this does not work well with multi-repo checking.

`meta` has not much downloads on npm, is this constellation not so much used?

**Comment by gnidan** [comment]
`meta`'s creator was/is part of ConsenSys, so I heard of it via his recommendation.

I've been generally quite happy with the process for Truffle's use case. We looked at other tools / methodologies before deciding on `meta` and determined that it was the best option considering the existing code structure and processes. It's been a [perhaps tenuous] team belief that a "poly-repo" setup is worth a bit of engineering overhead, that it helps in the effort towards clean separation of concerns via small, cohesive libraries.

Of course, there is still the engineering overhead, and certainly more to come. For instance, we had decided to expand on `meta` with `meta-pkgs` (to handle dependency graph traversal), and we'll likely continue to improve the process with additional plugins or improvements.

Some known limitations / sticking points right now are:
- Releases with changes in lots of repos take about 2 hours to complete.
- There's been a handful of tweaking required since we set up the CI infrastructure, and there are still minor outstanding issues
- It requires extra attention toward information dispersal / process documentation, which has introduced nonzero amounts of friction for community contributors

All in all though, I think we've all been pretty happy with the process. And once we set up good continuous deployment, we'll be a lot closer to "ideal".

To your question: yes it is "as easy as described", as far as getting cross-repo changes to link up—just use the same branch name across repos. We specifically targeted this use case, so it should simply work.

Would be curious to hear your thoughts on what is non-ideal and/or confusing, @lazaridiscom! Thanks for bringing this up.

Oh, by the way, some links:
- [`meta-pkgs`](https://github.com/trufflesuite/meta-pkgs)
- [CI repo](https://github.com/trufflesuite/ci), see [`bin/run_tests`](https://github.com/trufflesuite/ci/blob/master/bin/run_tests)
- [Common .travis.yml file](https://github.com/trufflesuite/truffle-migrate/blob/develop/.travis.yml) that can be the same for all repos

**Comment by lazaridiscom** [comment]
> that it helps in the effort towards clean separation of concerns via small, cohesive libraries.

Agree here, and the problems start with git and github, which do not allow the above "by design".

> Would be curious to hear your thoughts on what is non-ideal and/or confusing

Non-Ideal: git

Non-Ideal: github (introduces problems inherited from git, and adds its own)

As for `meta`: it seems like `it works` (possibly "around the core problems"). And if i would be further developed, it seems that I could be useful for other (= more) projects.

The only thing is: applying a command to all subdirs just 'feels' not right. But it's may be the only possible solution to overcome git's weaknesses.

The good things with this solution is: 

I can decide which other repos (modules / subssystems etc.) I can add to my "mega" (meta) command.

## Naming

* `meta`, i would prefer `project` or `pj`
* `dependencies`, i would prefer `subsystems`

But naming is of course a tiny desaster for itself.

## Other Solutions

(not sure if this covers the cross-repo checkin)

* git submodules (which has weaknesses, which could be addressed by a wrapping-cli around git, having the ability to address a few more weird git issues by e.g. adding convenience commands. Possibly such ssolutionss exist already

* MetaMask uses "clone into node_modules", but this seems limited.

Are you aware of other solutions to this problem? (e.g. those that you rejected during your initial evaluation ? )

**Comment by lazaridiscom** [comment]
I could be worth to see "The Opposite Viewpoint", here of a "monorepo" fanatic:

https://www.drmaciver.com/2016/10/why-you-should-use-a-single-repository-for-all-your-companys-projects/

The thing is: especially on github, there are practical limitations, e.g. the commit-messages (how can someone filter them) or the Issues filed (excessive amounts of issues).

I insist: the core-problem here is git itself, and github.

**Comment by lazaridiscom** [comment]
@gnidan , had you tried google's `repo` ?

**Comment by cgewecke** [comment]
@lazaridiscom Thanks for opening this - super interesting topic. I hope you don't mind but I'm going to close this issue for house-keeping since modifying the project structure and it's management isn't on our near-term road map. 

Leaving a link [here](https://source.android.com/setup/using-repo) to google's `repo` in case we revisit this.

**Comment by lazaridiscom** [comment]
@cgewecke , fine for me. I will assume that you did not try `repo` yet, so I take it on my eval list together with `meta`

**Comment by cgewecke** [comment]
@lazaridiscom Yes correct, I don't think either of us have tried `repo`. Would love to hear your impressions though.

**Comment by lazaridiscom** [comment]
@cgewecke , @gnidan - I saw you switched to a mono-repo.

You have any regrets, or does all work out fine now?

**Comment by lazaridiscom** [comment]
Nice, will keep it in mind for monorepo stuff!
