### ISSUE TITLE
Truffle Error-VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by ayushtchetu** [trufflesuite/truffle#859]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
I am creating test case of solidity in truffle and my solidity function is given below for which I am creating test cases
```
function isValidBuyer(uint256 buyTokenQty, uint256 senderValue) public  constant returns (bool)
    {
        if(!isUserExist(msg.sender))
        {
            msg.sender.transfer(senderValue); //Refund Ether
            return false ; 
        }
        else 
        {
            return true ;
        }
    }

```
And my test cases is as given below
```
it('TCC001: should check invalid buyer and should return false',   async () => {
let tempRes1=await instChain.isValidBuyer(100,1,{from:account2,gas:'220000'});

 assert.isTrue(!tempRes1);
}); 

```
While testing if clause of function in this test I am getting error VM Exception while processing transaction: revert One interesting case is in function isValidBuyer() when I am passing 1 wei it gives above mentioned exception but when I send 0.99 or less it gets execute successfully without error and returms false as expected..

## Expected Behavior

Should transfer ethers and return false

## Actual Results

-VM Exception while processing transaction: revert

## Environment

* Operating System: Windows 8 64 bit
* Ethereum client:
* Truffle version (`truffle version`): 4.1.3
* node version (`node --version`): 9.7.1
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@ayushtchetu. Your method changes state and will return a transaction receipt rather than boolean value.  

Could you try removing the `constant` modifier as well as the function return logic? Instead of checking for true/false, test the recipient account for an increase of value after the method successfully executes using [web3 methods](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetbalance). You might also want to test the contract balance before executing `isValidBuyer` to verify that the contract has ether to send. 

If the value you transfer is tiny (1 wei is the lowest possible value) it will be dwarfed by the gas costs of executing the transaction. Your ganache accounts are automatically seeded with 100 ether so you should be able to send larger amounts without running out.

**Comment by cgewecke** [comment]
@ayushtchetu I'm closing this because seems like a solidity usage issue rather than something truffle specific. Please feel free to re-open if you believe there is a bug on our end. Thanks!
