### ISSUE TITLE
compiler optimization broken since v4.0.6

### ISSUE THREAD

**Issue by chris-shyft** [trufflesuite/truffle#866]
using truffle compile --all:

truffle v4.0.7+ (tested all releases via "npm install -g truffle:@4.0.7", "npm install -g truffle:@4.1.0", etc until the latest 4.1.3) 

![screen shot 2018-03-24 at 3 08 15 am](https://user-images.githubusercontent.com/34154131/37861531-2135bc94-2f12-11e8-80a4-8228511073a3.png)

truffle v4.0.6 "npm install -g truffle:@4.0.6"

does indeed respect the 

solc: {
        optimizer: {
            enabled: true,
            runs: 5000000
        }
    }

commands within truffle.js. changing enabled to false does indeed result in less optimized contracts (1.9mb vs the 1.8mb for "ShyftKycContract" as detailed)

![screen shot 2018-03-24 at 3 12 52 am](https://user-images.githubusercontent.com/34154131/37861532-2317cf2a-2f12-11e8-97d6-c69b32b5fdba.png)

I've done by best to track down where or why this occurred, and the logic seems sound within the command structure (still using "solc": "^0.4.19" to this day), and the compiler passing options etc.

wondering what the fix for this might be.

**Comment by cgewecke** [comment]
@chris-shyft Thanks for such a clear report. 

Starting in 4.0.7, the artifact contains 2 versions of the AST - the legacyAST and solc's newer AST. This duplication was necessary because `truffle-debugger` requires the latter and it's possible that users consume former as well.  From what I understand of the above, your proxy measurement for optimization is the size of the artifact file. 

I think in this case we'd have to compare bytecode / binary sizes directly to determine that the optimizer behaving differently between versions. Those are available as a key on the artifact, in addition to lots of other stuff like the ABI, AST, etc.

Out of curiosity, what would be your 'top-level' bug description for this? Are you trying to publish to etherscan and it's not happening?

**Comment by chris-shyft** [comment]
publishing to a ganache-cli running locally.

namely, I'm getting an "out of gas" when running with anything above 4.0.6, which is the same behaviour as removing the "optimize" flag when in remix and trying to publish the contract to the same ganache-cli instance.

**Comment by chris-shyft** [comment]
On closer inspection, I think I'm mistaken.

due to the nature of my build process, I missed the "--all" flag with the truffle compile process.
#lessons :D
