### ISSUE TITLE
Truffle develop don't support eth_sign

### ISSUE THREAD

**Issue by Giulio2002** [trufflesuite/truffle#867]
i have created a state channel with truffle,but truffle develop can't sign messages so i can't test it

**Comment by cgewecke** [comment]
@Giulio2002 Could you post reproduction steps? Are you reporting that [web3.eth.sign](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign) doesn't work in the develop console? 

It might be easier to work on this problem in a unit test you run with `truffle test` since it likely requires several setup steps to execute.

**Comment by Giulio2002** [comment]
I am using truffle develop and when I try to sign my message it say that web3.eth.sign is not implemented

**Comment by cgewecke** [comment]
@Giulio2002 I am not able reproduce this error (see below)

![screen shot 2018-03-26 at 8 55 40 am](https://user-images.githubusercontent.com/7332026/37917578-a1aa7e4c-30d3-11e8-88d0-c932ba2578ad.png)

**Comment by Giulio2002** [comment]
What version of truffle do you use

**Comment by Giulio2002** [comment]
Maybe the problem is my truffle version

**Comment by Giulio2002** [comment]
I updated to latest now works
