### ISSUE TITLE
If i have an object of a bugged contract alive then I am able to write on the network even after truffle migration is run without any bug??

### ISSUE THREAD

**Issue by hello-i-am-venom** [trufflesuite/truffle#909]
## Expected Behavior

What you expected to happen.
I guess object is mapped with the previous contract (bugged one) but it might update values on the accounts which are used in
Its a feature or problem

## Environment

* Operating System: fedora 27
* Ethereum client: ganache
* Truffle version (`truffle version`): 4.1.7
* node version (`node --version`): 8.9
* npm version (`npm --version`): 5.6

**Comment by cgewecke** [comment]
Hello @hello-i-am-venom. 

Could you give a simple example of the issue you've described?

**Comment by hello-i-am-venom** [comment]
* make a contract with some loop hole
* make an instance of that contract and make it live truffle console
* update the contract remove the bug
* run 'truffle migrate --reset'
but you can use that previous instance of that contract

**Comment by cgewecke** [comment]
@hello-i-am-venom Yes, this is expected. `migrate reset` doesn't erase the previous contract from the chain but runs migrations again from the beginning. Migrations are staged in sequences because in a real project deployment you might do them over a long period. More on this [here](http://truffleframework.com/docs/getting_started/migrations#running-migrations).  

If you'd like to access a specific instance in the console you can use the `MyContractName.at(<address>)` method from `truffle-contract` ([docs here](https://github.com/trufflesuite/truffle-contract#contract-abstraction-api)). The address the contract was created at should be listed in the migrations log output.

**Comment by cgewecke** [comment]
@hello-i-am-venom Are you satisfied with this explanation? Is this issue closable?

**Comment by cgewecke** [comment]
Closing - @hello-i-am-venom please ping if you continue to have trouble with this.
