### ISSUE TITLE
4.1.7 test network doesn't work

### ISSUE THREAD

**Issue by Arvanaghi** [trufflesuite/truffle#912]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle test` says cannot connect to Ethereum client when run after `truffle init`. This may be a `truffle init` problem, as I don't run into this when I `truffle unbox` the MetaCoin project.

## Steps to Reproduce

`truffle test`

## Expected Behavior

normal tests to rumn

## Actual Results

```
.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10
  this.stack = (new Error(message)).stack;
^

Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```

## Environment

* Operating System: OSX
* Ethereum client:
* Truffle version (`truffle version`): 4.1.7
* node version (`node --version`): v8.9.0
* npm version (`npm --version`):  5.8.0

**Comment by cgewecke** [comment]
@Arvanaghi I can't reproduce this. On OSX, using 4.1.7 I ran 
+ `truffle init` in an empty folder. 
+ `truffle test`.

**Output**: There's a compilation warning but that's it:


![screen shot 2018-04-23 at 9 54 18 am](https://user-images.githubusercontent.com/7332026/39141345-663e15f2-46dc-11e8-8ece-565d0f9f4dad.png)


Is there something missing in the reproduction steps?

**Comment by Arvanaghi** [comment]
It was my test file causing this message to appear. My mistake.

**Comment by cbruguera** [comment]
@Arvanaghi Any details on what was the actual cause of the message? Cause I'm having the same issue, still not finding the error.

More context: tests run perfectly well within `truffle develop` and through `solidity-coverage`, but fail with the "could not connect" upon `truffle test`. Even more baffling: the tests actually run (and pass), just at the end the error message is displayed.

**Comment by cgewecke** [comment]
@cbruguera Could you post the contents of your `truffle.js`?

**Comment by vauvenal5** [comment]
@Arvanaghi can you please describe what the issue was? I am discovering the same problem. When running "truffle test" all tests pass and in the end the error message is thrown. If I run them in "truffle develop" everything is fine, also when I configure a network in truffle.js they pass without any issues.

@cbruguera did you find the issue?

**Comment by cbruguera** [comment]
Apologies, I haven't been able to reproduce the error. And I can't recall right now what was the truffle-js file that was being used at the time (I'm working on multiple different projects). Since in my latests test runs I haven't seen this error, I'll regard it as "fixed" for me.

I'll give notice in this thread in case I see the error again.
