### ISSUE TITLE
how to use other smart contract token in a new smart contract ?

### ISSUE THREAD

**Issue by wadelee1986** [trufflesuite/truffle#966]
how to make an  External Function Calls  in smart contract  ?

**Comment by cgewecke** [comment]
@wadelee1986 You can interact with an existing contract within Solidity if you have its deployed address and its source code There's a nice tutorial about how to do this [here](https://dappsforbeginners.wordpress.com/tutorials/interactions-between-contracts/)

**Example**
```javascript
pragma solidity ^0.4.18;

contract HelloToken {
  event SaidHello(address caller);

  function hello() public {
    emit SaidHello(msg.sender);
  }
}

contract Caller {
  function callHelloToken(address deployed) public {
     HelloToken token = HelloToken(deployed); // Get HelloToken instance at some address
     token.hello(); // Use token contract
  }
}
```

Closing because this is a question about how to use the Solidity language rather than a problem specific to Truffle.
