### ISSUE TITLE
Errors unhelpful when accidentally deploying interfaces / abstract contracts. 

### ISSUE THREAD

**Issue by Mc01** [trufflesuite/truffle#971]
## Issue

Truffle contract (https://github.com/trufflesuite/truffle-contract) shows incorrect messages and behaves incorrectly during migrations.

## Steps to Reproduce

Clone and setup this repo: https://github.com/Mc01/TruffleTest

## Expected Behavior

1. Contract should not be deployed and Truffle should throw informative exception what's the reason. Truffle should not allow to enter method after deployment and fail with interaction on contract properties.
2. Truffle should show parsed messages by default - the default error `The contract code couldn't be stored, please check your gas amount.` is misleading and ambiguous. `Error: {ContractName} has no network configuration for its current network id ({NetworkId}).` is preferred, however also invalid for this case. The best would be information about whats the issue with contract code or in what process it fails.

## Actual Results

Contract seems to be deployed successfully and informs about invalid network configuration.

Default message: `This should throw during deploy and do not allow calling contract inside
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.`

Caught internal message: `Error: {ContractName} has no network configuration for its current network id ({NetworkId}).`

## Environment

* Operating System: OSX
* Ethereum client: Ganache App/Ganache CLI/Truffle Develop
* Truffle version (`truffle version`): 4.1.11
* node version (`node --version`): v9.6.1
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@Mc01 Thank you for this excellent bug report, really appreciate the reproduction case.  

If I understand correctly - the error is being triggered by an attempt to deploy an abstract contract. We should definitely handle this case better - there's a related issue from some time ago [here](https://github.com/trufflesuite/truffle/issues/796). 

The error you're seeing comes from one of Truffle's dependencies: `web3`. When it executes a deployment and receives a receipt, it performs [a check](https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L96-L157) to verify that code exists at that address. An abstract contract has no data associated with it so there is nothing there.

If you look at the `IncorrectChild` artifact in the `build` folder after running `truffle-compile`,  you will see it has no bytecode, so nothing is being written to the chain:

```
"bytecode": "0x",
"deployedBytecode": "0x", 
```

We should detect cases where someone attempts to deploy a contract with an empty binary and either reject or skip those contracts. 

As a side note - I noticed in your `truffle.js` you're using a form of provider instantiation that no longer works with the latest `HDWallet`. Because of some recent changes in that Library, these provider calls should be wrapped in a function closure, as shown in the docs [here](http://truffleframework.com/docs/advanced/configuration#providers).

**Comment by Mc01** [comment]
@cgewecke Thanks for quick answer. 

Here's the equivalent message from Remix IDE when trying to deploy this contract `This contract does not implement all functions and thus cannot be created.`. So to confirm - yes, it is an abstract contract.

Btw, thanks for pointing out these issue with provider and `HDWallet`. Haven't noticed that it already changed. Will definitely use that in my own projects 👍

**Comment by gideongrinberg** [comment]
Still an issue.
