### ISSUE TITLE
Only display Errors when compiling

### ISSUE THREAD

**Issue by 4000D** [trufflesuite/truffle#975]
## Issue

In `truffle compile`, all Warnings and Errors displayed at the same time.
To capture stderr without warning, I have to run `truffle compile | grep Error`.
I think that it is very concise and readable not to display warnings if errors exists.

## Steps to Reproduce

`truffle compile` with a contract having both of compiler errors and warnings.

## Expected Behavior

If errors exists, displaying errors would be better.

## Actual Results

Errors and Warnings are displayed in a single mingled stderr.

## Environment

* Operating System: maxosX
* Truffle version (`truffle version`): 4.1.8 (solc 0.4.24)
* node version (`node --version`): 8.9.1
* npm version (`npm --version`):

**Comment by cgewecke** [comment]
@4000D Thanks for opening. Your idea about first showing the errors, then showing the warnings is a good one, although I think your work around is also pretty nice. 

```shell
$ truffle compile | grep Error # <-- Nice!
```

Leaving some notes / context here for further consideration:

+ the recent spate of warnings are related to `solc`'s pending upgrade to a new version which will have many breaking changes. With v0.5.0 they will be errors. Sort of an idle question but: will warnings decrease (a lot) soon? 

+ my impression is that the Solidity engineers do not want warnings turned off or filtered out. Solidity is a special language case because its programs typically manage funds in a no-recourse financial transaction system - all warnings should be taken seriously. Given a mix of warnings and errors, it may be best to start at the top fixing each one in succession. . .

+ Maybe we should colorize the solc output: warnings => yellow, errors => red.

**Comment by taylorjdawson** [comment]
@cgewecke Yes, I agree. Please colorize the solc output that would be extremely helpful! It would be helpful to either rename this issue or create a new issue as: **Colorize the solc output**.

**Comment by cgewecke** [comment]
@taylorjdawson After this issue was opened I happened to see a [great PR](https://github.com/ethereum/solidity/pull/3046) over at solidity which suggests they're moving in this direction themselves. . .it looks like there's active work there if you follow the links to corresponding pull requests.
