### ISSUE TITLE
Tests order

### ISSUE THREAD

**Issue by mikiw** [trufflesuite/truffle#990]
Hello, I have problem with truffle. When i run truffle test per single file for example:
"truffle test Contract.js" everything works fine and all single tests passes but when I run full test "truffle test" only first of them pass like this:

Contract.js (pass)
Toke.js (fail)
Crowdsale.js (fail)

Toke.js (pass)
Contract.js (fail)
Crowdsale.js (fail)

any ides why?

**Comment by cgewecke** [comment]
@mikiw A common cause of this is accidentally making a `describe` or `contract` callback async. 
```javascript
// Example
describe('test suite', async function(){ //  <-- Mocha does not support this.
  it('should ...', async function(){     //  <-- Ok.
    ...
  });
})
```

You might also comb through your async code and double check that every promise is being waited for correctly.

**Comment by mikiw** [comment]
in our company we think that it related with https://github.com/trufflesuite/ganache-core/pull/81 bug

we implemented time controller and addSeconds(X) where X is enormous number like 10000000 and it helped

**Comment by cgewecke** [comment]
In the example you've given, the tests change order which suggests a problem with the way your async code interacts with mocha. Mocha guarantees that it will run each `describe` and `it` block in a strict sequence so: 
+ describe blocks should never run out of order - they're executed synchronously.  
+ if promises are being correctly handled in the `it` blocks, they should timeout or otherwise error when there is a problem.

**Comment by mikiw** [comment]
I figured out it later that orders is not important but something else like time related stuff

**Comment by cgewecke** [comment]
@mikiw Ah ok - if this is addressed by [ganache #81](https://github.com/trufflesuite/ganache-core/pull/81) is it ok if we close here and track the issue there?

**Comment by cgewecke** [comment]
Closing (see above)

**Comment by mikiw** [comment]
yes sure
