### ISSUE TITLE
Why do you bundle all dependencies for an npm module?

### ISSUE THREAD

**Issue by Levino** [trufflesuite/truffle#994]
On build and before publication to **npm** you create a webpack bundle, right? This bundle contains the source code of all dependencies. This is an anti pattern as far as I know. This only makes sense to me if you are bundling an application for usage in html code in the client (so if you want to publish it on a CDN but not npm). Npm packages should name their dependencies and not bundle them in. If the consumer of the package wants to use your package in the browser, they should bundle all the dependencies themselves. Anyhow I do not understand how truffle can be used in the browser.

**Comment by MoMannn** [comment]
+1 

This is an issue I came across when trying to use a custom web3. It is very inconvenient to fork truffle just to change the web3 dependency.

**Comment by cgewecke** [comment]
@Levino 
@MoMannn 
@xpepermint

Unbundled truffle is available as [truffle-core](https://www.npmjs.com/package/truffle-core), which exposes a `cli.js` so it can be used as command line utility on its own.

We're migrating the project architecture to a [Lerna monorepo](https://github.com/lerna/lerna) shortly so that everything is in one place and dependencies like `web3` sit in a single location. Modifying the project should become a lot easier. I believe Truffle will continue to be published as a webpack although perhaps there should be some discussion about this. 

I think the decision to bundle was made more than a year ago when package-locking was less normative and semver coherence was less rigorously followed in truffle's Ethereum dependencies. It's been very effective at squashing cross-platform installation issues and speeding up installation. Truffle used to take a couple minutes to install and the issues were filled with dep problems. It now takes a few seconds - the goal was to make something that had turned into a minor nightmare super simple and reliable for new users. 

@xpepermint Not sure if this helps but truffle also publishes a nightly experimental build that runs web3 1.0-beta.33 under the hood. It's available on [npm as darq-truffle@next](https://www.npmjs.com/package/darq-truffle).

**Comment by xpepermint** [comment]
Thanks @cgewecke for the explanation. We are using our own Web3 version thus peerDependencies would help us run that with the default Truffle version. Now we are forking truffle project to achieve that.

**Comment by Levino** [comment]
> Thanks @cgewecke for the explanation. We are using our own Web3 version thus peerDependencies would help us run that with the default Truffle version. Now we are forking truffle project to achieve that.

Sorry, but I do not understand. Could you elaborate how this would help? Currently web3 is bundled into the final .bundle.js. What do the peerDependencies have to do with what ends up in the bundle when it is created before publication of truffle to npm?

**Comment by Levino** [comment]
> Unbundled truffle is available as truffle-core, which exposes a cli.js so it can be used as command line utility on its own.

How about fixing the Readme of `tuffle-core` and add this information? It seems it is just the `truffle` readme.

**Comment by xpepermint** [comment]
@Levino yeah. Because of the webpack this is not possible. If Truffle would be a usual NodeJS project then pearDependencies should do the trick :).

**Comment by Levino** [comment]
> @Levino yeah. Because of the webpack this is not possible. If Truffle would be a usual NodeJS project then pearDependencies should do the trick :).

When you add a local dependency to `web3` the subdependency `web3` of any other dependency of will be overwritten. It does not matter whether `web3` is a subdependency oder a subpeerdependency. In your `node_modules` folder will always be only one `web3`.

**Comment by Levino** [comment]
> I think the decision to bundle was made more than a year ago when package-locking was less normative and semver coherence was less rigorously followed in truffle's Ethereum dependencies. It's been very effective at squashing cross-platform installation issues and speeding up installation. Truffle used to take a couple minutes to install and the issues were filled with dep problems. It now takes a few seconds - the goal was to make something that had turned into a minor nightmare super simple and reliable for new users.

I get your point. But are there any other **high quality** projects who use this pattern? This sounds to me a little bit like a hack to solve the problem, that `truffle` has too many inapt users who do not have their sh*t together when it comes to node and npm. And as soon as people use `truffle-core` you have the same issues than before. So you kind of have a gatekeeper for the script kiddies who cannot tell their arse from their elbow but they still can end up creating annoying issues that `truffle-core` won't build on their misconfigured windows setup. I would rather say these users should not be doing any smart contract coding whatsoever. You are giving machine guns to monkeys.

**Comment by Levino** [comment]
I guess my original issue is resolved.

**Comment by cgewecke** [comment]
@levino LOL ok. 

Just making a note here for future reference that once we're in the monorepo we should consider publishing an un-bundled version with each release at some tag so people who prefer this have easy acccess. 
```shell
truffle@unpacked # or something
```
